### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by roflmuffin** [roflmuffin/CounterStrikeSharp#1]
Investigate work required to support 64 bit Windows servers
- [ ] CMake modifications
- [ ] Windows .NET Runtime
- [ ] CI matrix builds
- [ ] Managed Code Windows Support (marshalling/DllImport)

**Comment by a793181018** [comment]
Character，I think that CounterStrikeSharp should be build by Visual-Studio

**Comment by a793181018** [comment]
What time the project support Windows10 or win 11

**Comment by a793181018** [comment]
I have done some work for CounterStrikeSharp,but failed.

**Comment by roflmuffin** [comment]
Closed by #52, thanks to @laper32 and Ciallo-Ani for their hard work.
