### ISSUE TITLE
Is the inability to use plugins with version 0.56 due to the plugins not being updated?

### ISSUE THREAD

**Issue by 1370533448** [roflmuffin/CounterStrikeSharp#100]
As I was investigating why my server was crashing, I noticed that CSS had been updated to version 0.56. After I replaced it, all the CSS plugins seemed to lose their functionality. I saw that some people had reported issues with version 0.54 and found that downgrading to 0.53 rectified the problem, so I did the same. Indeed, all the plugins were restored. This is the latest CS2 server version updated today, running on a Windows system.

**Comment by roflmuffin** [comment]
Please at least provide log messages of startup, there is not enough information in the issue
