### ISSUE TITLE
[Bug] `player_hurt` event: Damage and hits data reported via CSS is not matching in-game data

### ISSUE THREAD

**Issue by miguno** [roflmuffin/CounterStrikeSharp#103]
I am tracking damage taken/given in a round in my plugin.  Here, I noticed that there can be a discrepancy between the CSS-reported data and the “truth” (more on that in a moment).

**Expected behavior:**
The totals for damage and hits reported by CSS (accessed via the `player_hurt` event) match what CS2 reports in-game at the top of the screen at round end (the latter is the ground truth).

**Actual behavior**
- It happens that a player is killed, but the total damage taken by that player is not exactly 100 (starting health at the beginning of the round), but only 99, 98, or even 97. Same for damage given by the attacker(s).
- Similarly, the number of hits taken by that player can be less than the true number (same for number of hits given by the attacker(s)).

This can be seen when comparing the CSS totals of damage taken/given and number hits taken/given vs. what CS2 is reporting at the top of the screen at round end.

**Possible cause**
Rounding errors? It looks like some part of the code chain could be using `float`s vs. another part uses `int`s (CSS itself does use `int`s, for example), which may introduce rounding errors. This hypothesis is supported by the observation that the data discrepancy is more likely to happen when a player is taken many hits (e.g., Glock body shots; multiple attackers = more `float`s/`int`s will be generated and summed up) vs. few hits (e.g., AK headshot, AWP shot; single attacker).

**Comment by switz** [comment]
This is a bug in CS2, I have reported it to the team, but have not heard back. Here's some more context: https://twitter.com/popflashsite/status/1719831502526038173

**Comment by miguno** [comment]
Thanks, this does sound very related.

Did you also notice that the in-game UI of CS2 (here: top of screen damage given/taken stats at round end) *is* always showing correct data, but only the data exposed via the events is apparently inaccurate?  So it seems there are two code paths at play: whatever CS2 is doing internally for its own damage tracking, perhaps using a different way to access the damage data, vs. what is exposed via events such as `player_hurt`.

Asking because the linked tweet wasn’t totally clear to me whether it’s “just” a data-in-events issue vs. CS2 actually failing to register a kill properly. From what I have observed, it is the former, not the latter. In other words: CS2 will correctly register a player kill itself (player will die, kill is shown in kill feed at the right time, end-of-round damage stats are shown correct damage numbers and number of hits, etc.), but the data we have access too is showing the reported inaccuracies.

**Comment by miguno** [comment]
Additional context so it's not just in an external tweet.

When you print event data for `player_hurt`, you can see output like the following when player A attacks player B:

```
# Starting health was 100hp.
@event.Health:  60 | @event.DmgHealth: 40
@event.Health:  35 | @event.DmgHealth: 24   <-- 60-35=25 != 24
@event.Health:  11 | @event.DmgHealth: 24
@event.Health:   0 | @event.DmgHealth: 25
```

**Comment by miguno** [comment]
The current workaround I am using is to track "health remaining" via `@event.Health` in the `player_hurt` event to compute "health deltas" and thus, indirectly, to compute damage taken/given.  This approach makes the tracked data consistent with CS2 (damage reported in the scoreboard at the top of the screen etc.).

**Comment by roflmuffin** [comment]
We can track this information now using a TakeDamage dynamic hook, if you wanted to try that (example in test plugin).
