### ISSUE TITLE
CounterStrikeSharp wouldnt start

### ISSUE THREAD

**Issue by nikolayRush** [roflmuffin/CounterStrikeSharp#108]
I using Windows Server 2022
I installed metamod last version, and trying Counterstrikesharp last version with Runtime, but then i start cs2 got this errors

L 11/21/2023 - 11:30:10: [META] Failed to load plugin addons/counterstrikesharp/bin/win64/counterstrikesharp: ═х эрщфхэ єърчрээ√щ ьюфєы№.

L 11/21/2023 - 11:30:10: [META] Loaded 0 plugins.

meta list
Listing 1 plugin:
  [01] <ERROR>

**Comment by KillStr3aK** [comment]
resolved by installing Visual C++ components

**Comment by JJaery7545** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/150849188/f03523f5-44bc-47d9-8b73-225fc5a1876f)
