### ISSUE TITLE
[Bug?] Admin @css/root

### ISSUE THREAD

**Issue by ChocOranger** [roflmuffin/CounterStrikeSharp#125]
Using plugin CS2Rcon it requires the admin flag @css/rcon. Setting that flag for my admin works as expected however using @css/root doesn't grant admin access to the plugin.
Is @css/root bugged or am I missing something in how it is used?

The plugin code looks correct to me
https://github.com/LordFetznschaedl/CS2Rcon/blob/be0cef22665d7e6f5b4882dc02d48b79ce84d046/CS2Rcon/CS2Rcon.cs#L26

**Comment by roflmuffin** [comment]
The permissions don't work in the same way as source mod, the `root` does not imply all of the other permissions; admins will need to explicitly have the `@css/rcon` flag or be in a group with `@css/rcon` to enable use of the command.

**Comment by crashzk** [comment]
@roflmuffin but wouldn't it be possible to say that if you have access to @css/rcon you would have access to all flags, even without configuring it for the admin?

Or could this be a problem?

**Comment by ChocOranger** [comment]
The documentation states
@css/root # Magically enables all flags and ignores immunity values. (Same wording used in Sourcemod)

What is @css/root intended purpose?

**Comment by adammyllykoski** [comment]
My two cents here would be to simply change the behavior, and let the `@css/root` flag's intended purpose be to act as a "superadmin". If I add a player as a "root" admin, I would expect them to get access to all commands, which in my world should include both @css flags and perhaps also all custom flags added by plugin creators. This would also match the behavior people are used to from SourceMod. 

As of right now, this flag doesn't make any sense, IMO. 

Managing flags for each and every plugin, for every admin, may become a time-consuming task over time when adding new plugins that require new flags. Let's remember that many just want to have plugins to enhance their experience with their friends/teammates, and not necessarily use it for public community servers where fine-tuned control may be needed.

**Comment by ChocOranger** [comment]
I fully agree with @adammyllykoski and @crashzk (although I think he meant @css/root) that it should get access to all flags. People are already misunderstanding its purpose.
The best place to add a master admin is in the framework then all users get access rather than everyone having to create their own.

I do however feel it should be all flags not just @css ones.

**Comment by roflmuffin** [comment]
@zonical Do you have thoughts on whether we should make @css/root a wildcard flag?

**Comment by zonical** [comment]
I have two alternatives:
1) add a new key to `admins.json` which specifies an all-command override
2) turn the `@css/root` flag into `@root`, so it's not linked to any plugin or system

I'm not a *massive* fan on wildcard flags but I think option 2 would be the closest thing to that

**Comment by crashzk** [comment]
> 2. turn the `@css/root` flag into `@root`, so it's not linked to any plugin or system
> 
> I'm not a _massive_ fan on wildcard flags but I think option 2 would be the closest thing to that

Option 2 would be the best option for me, even becoming a wild card as mentioned. I believe it would be the best, since AMXModX the root flag would be used as superadmin, with it access to all flags and should only be used on trusted players.

Many users only use them when they own the server and on players they trust a lot;

Anyway, I'm still in favor of making it a wildcard, a super admin flag.

**Comment by zonical** [comment]
I have another idea.
If there is a `root` flag for a type of plugin/system, it should allow the person to have all of those permissions.

E.g `@css/root` grants all permissions under the `@css` domain, `@kzsurf/roof` grants all permissions under the `@kzsurf` domain.

Thoughts?

**Comment by KillStr3aK** [comment]
> I have another idea. If there is a `root` flag for a type of plugin/system, it should allow the person to have all of those permissions.
> 
> E.g `@css/root` grants all permissions under the `@css` domain, `@kzsurf/roof` grants all permissions under the `@kzsurf` domain.
> 
> Thoughts?

I like this

**Comment by ChocOranger** [comment]
> I have another idea. If there is a `root` flag for a type of plugin/system, it should allow the person to have all of those permissions.
> 
> E.g `@css/root` grants all permissions under the `@css` domain, `@kzsurf/roof` grants all permissions under the `@kzsurf` domain.
> 
> Thoughts?

Good idea as long as there is also a master admin like your @root suggestion.

**Comment by Dliix66** [comment]
> I have another idea. If there is a `root` flag for a type of plugin/system, it should allow the person to have all of those permissions.
> 
> E.g `@css/root` grants all permissions under the `@css` domain, `@kzsurf/roof` grants all permissions under the `@kzsurf` domain.
> 
> Thoughts?

Agreed, but as @roflmuffin said, keep the @root to give all @plugin/root access
