### ISSUE TITLE
Server Crash v71

### ISSUE THREAD

**Issue by jinnsTaRR** [roflmuffin/CounterStrikeSharp#128]
[EROR] (cssharp:Core) Error invoking callback
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
--- End of inner exception stack trace ---
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

this message appears in console.log every 2-4 minutes, is it my mistake or from the plugin? pls help

**Comment by johnoclockdk** [comment]
this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin

**Comment by jinnsTaRR** [comment]
Are you sure? How you know that its from advertisent?? I See nothing only cssharpAm 25.11.23 um 00:27 schrieb johnoclockdk
                
            
            
                
                    Von: "johnoclockdk" ***@***.***>Datum: 25. November 2023An: "roflmuffin/CounterStrikeSharp" ***@***.***>Cc: "Author" ***@***.***>,"jinnsTaRR" ***@***.***>Betreff: Re: [roflmuffin/CounterStrikeSharp] Server Crash v71 (Issue #128)
                
                
this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin

**Comment by crashzk** [comment]
> Are you sure? How you know that its from advertisent?? I See nothing only cssharpAm 25.11.23 um 00:27 schrieb johnoclockdk Von: "johnoclockdk" ***@***.***>Datum: 25. November 2023An: "roflmuffin/CounterStrikeSharp" ***@***.***>Cc: "Author" ***@***.***>,"jinnsTaRR" ***@***.***>Betreff: Re: [roflmuffin/CounterStrikeSharp] Server Crash v71 (Issue #128) this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Read the error log carefully:
```
at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
```

**Comment by johnoclockdk** [comment]
> > Are you sure? How you know that its from advertisent?? I See nothing only cssharpAm 25.11.23 um 00:27 schrieb johnoclockdk Von: "johnoclockdk" _**@**_._**>Datum: 25. November 2023An: "roflmuffin/CounterStrikeSharp" _**@**_.**_>Cc: "Author" _**@**_._**>,"jinnsTaRR" _**@**_.**_>Betreff: Re: [roflmuffin/CounterStrikeSharp] Server Crash v71 (Issue #128) this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> Read the error log carefully:
> 
> ```
> at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
> ```

what crash said

**Comment by jinnsTaRR** [comment]
> > Are you sure? How you know that its from advertisent?? I See nothing only cssharpAm 25.11.23 um 00:27 schrieb johnoclockdk Von: "johnoclockdk" _**@**_._**>Datum: 25. November 2023An: "roflmuffin/CounterStrikeSharp" _**@**_.**_>Cc: "Author" _**@**_._**>,"jinnsTaRR" _**@**_.**_>Betreff: Re: [roflmuffin/CounterStrikeSharp] Server Crash v71 (Issue #128) this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> Read the error log carefully:
> 
> ```
> at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
> ```

now i fixed this with advertisement but now this still appears in console : 

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

this is not from advertisiment

**Comment by crashzk** [comment]
> > > Are you sure? How you know that its from advertisent?? I See nothing only cssharpAm 25.11.23 um 00:27 schrieb johnoclockdk Von: "johnoclockdk" _**@**_._**>Datum: 25. November 2023An: "roflmuffin/CounterStrikeSharp" _**@**_.**_>Cc: "Author" _**@**_._**>,"jinnsTaRR" _**@**_.**_>Betreff: Re: [roflmuffin/CounterStrikeSharp] Server Crash v71 (Issue #128) this is not a issue with cs# is issue with Advertisement made by @partiusfabaa and you need to create it on his github for the plugin —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > Read the error log carefully:
> > ```
> > at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
> > ```
> 
> now i fixed this with advertisement but now this still appears in console :
> 
> at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Delegate.DynamicInvokeImpl(Object[] args) at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
> 
> this is not from advertisiment

Did you restart the server after fixing the advertsiment plugin?

In any case, it may be related to this issue: https://github.com/roflmuffin/CounterStrikeSharp/issues/123

In this case, just waiting for the correction!

**Comment by roflmuffin** [comment]
Closing this as the error stack is related to a specific plugin
