### ISSUE TITLE
Extend Round Time

### ISSUE THREAD

**Issue by Kubadesek** [roflmuffin/CounterStrikeSharp#130]
I will happy for feature to change roundtime.

**Comment by crashzk** [comment]
cvar **mp_roundtime** wouldn't be what you're looking for?

Or would it be overtime? If so, you would also have cvars in CS2 itself, just configure it to your liking.

**Comment by jinnsTaRR** [comment]
> I will happy for feature to change roundtime.

mp_roundtime
mp_roundtime_defuse
mp_roundtime_hostage 

put in in your game/csgo/cfg 
Casual: gamemode_casual_server.cfg
Competitive: gamemode_competitive_server.cfg

**Comment by Kubadesek** [comment]
I mean it change it by GameRules because concvars doesnt change it right now

**Comment by KillStr3aK** [comment]
you can access gamerules in code

**Comment by Kubadesek** [comment]
U tried but doesnt work

**Comment by Kubadesek** [comment]
CCSGameRules iRoundTime = GameRulesHandler.GameRules();
iRoundTime.RoundTime += 100;

its changed but doesnt do anything

**Comment by Kubadesek** [comment]
okay its works but doesnt update hud

**Comment by KillStr3aK** [comment]
> okay its works but doesnt update hud

probably it will work as intended when network states also sent to the clients (wip)

**Comment by P250** [comment]
In case anybody stumbles upon this, to update the HUD you have to call `Utilities.SetStateChanged(entity, "CCSGameRulesProxy", "m_pGameRules")` on the CCSGameRulesProxy "entity". Thank you Poggu for helping me with this.

**Comment by WeirdPhrog** [comment]
> CCSGameRulesProxy "entity"

What is that?

**Comment by razpbrry** [comment]
> > CCSGameRulesProxy "entity"
> 
> What is that?

var entity = Utilities.FindAllEntitiesByDesignerName<CCSGameRulesProxy>("cs_gamerules").First();
