### ISSUE TITLE
Documents for Native API such as FireEvent

### ISSUE THREAD

**Issue by FlowingSPDG** [roflmuffin/CounterStrikeSharp#137]
Hello, I was looking for API to fire event by CSS and found one inside of NativeAPI namespace.
Can we add document page like SourceMod? e.g. https://sm.alliedmods.net/new-api/events/FireEvent .
I'd like to add document to some APIs and contribute them under ``docs/src/content/docs/reference`` directory if that's okay.

**Comment by KillStr3aK** [comment]
`NativeAPI` contains native functions that are supposed to be wrapped around by a class that use those natives.
An auto generated doc is on the way tho

**Comment by FlowingSPDG** [comment]
Oh, so I guess it's better to use wrapped API instead?
haha I just realized that I could use already:
```cs
// OLD
var vote = NativeAPI.CreateEvent("vote_options",true);
        NativeAPI.SetEventInt(vote, "count", 2);
        NativeAPI.SetEventString(vote, "option1", "Yes");
        NativeAPI.SetEventString(vote, "option2", "No");
        NativeAPI.SetEventString(vote, "option3", "");
        NativeAPI.SetEventString(vote, "option4", "");
        NativeAPI.SetEventString(vote, "option5", "");
        NativeAPI.FireEvent(vote, false);

// NEW
var voteOptions = new EventVoteOptions(true)
        {
            Count = 2,
            Option1 = "Yes",
            Option2 = "No",
            Option3 = "",
            Option4 = "",
            Option5 = ""
        };
        voteOptions.FireEvent(false);
```

Awesome, thanks!
