### ISSUE TITLE
Player doesn't spawn when changing teams from spectator

### ISSUE THREAD

**Issue by ar1a** [roflmuffin/CounterStrikeSharp#139]
When switching teams from spectator to CT/T via code, the player does not spawn. When the player is in spectator and they type in `jointeam 0` in console, the player spawns as expected

This happens with both `ChangeTeam` and `SwitchTeam`. Respawning (from #114 )  the player immediately after, or on the next server frame has no effect.

easily reproducible

1. join spectator
2. `player.ChangeTeam(CsTeam.Terrorist);`
3. observe the player joins the team but is not spawned

**Comment by ar1a** [comment]
Multiple people in discord have run into this: 
https://discord.com/channels/1160907911501991946/1160925208203493468/1178548956016431205
https://discord.com/channels/1160907911501991946/1160907912445710479/1171653420827021343
https://discord.com/channels/1160907911501991946/1160907912445710480/1177507018588823613

**Comment by roflmuffin** [comment]
As mentioned in discord, these are valve methods and we have no control over how they actually affect the game.
