### ISSUE TITLE
EventPlayerJump is only triggered after a HotReload

### ISSUE THREAD

**Issue by Dliix66** [roflmuffin/CounterStrikeSharp#140]
Pretty easy to replicate:
- Start server, `EventPlayerJump` is never triggered
- Reload the plugin (either using `css_plugins reload` or updating the DLL)
- `EventPlayerJump` works fine

Might be affecting some other events

PS: I'm on build 76

**Comment by KillStr3aK** [comment]
I can confirm this

**Comment by itsBoats** [comment]
similar issue with Grenade Bounce event
