### ISSUE TITLE
RegisterEventHandler<T> seems to ignore HookMode

### ISSUE THREAD

**Issue by Dliix66** [roflmuffin/CounterStrikeSharp#149]
I was working with @KillStr3aK on updating killchat to give a kill to another player and I noticed a weird behavior:

This works fine:
```csharp
[GameEventHandler(HookMode.Pre)]
private HookResult OnEventPlayerDeath(EventPlayerDeath evnt, GameEventInfo _)
{
   Server.PrintToChatAll("test");
   evnt.Attacker = newAttacker;
   return HookResult.Changed;
}
```

However doing this does not work fine, the callback is called, message is printed but killchat is not updated:
```csharp
public class MyPlugin: BasePlugin
{
  public override void Load(bool hotReload)
  {
    RegisterEventHandler<EventPlayerDeath>(OnEventPlayerDeath, HookMode.Pre);
  }

  private HookResult OnEventPlayerDeath(EventPlayerDeath evnt, GameEventInfo _)
  {
     Server.PrintToChatAll("test");
     evnt.Attacker = newAttacker;
     return HookResult.Changed;
  }
}
```

The 2nd option behaves exactly as if I used the `GameEventHandler` Attribute with `HookMode.Post`

**Comment by roflmuffin** [comment]
That is strange because the code to register handlers calls the same internal method as the register event handler method

**Comment by KillStr3aK** [comment]
Might be related to #140?

**Comment by roflmuffin** [comment]
I can't replicate this locally. I ran a plugin with this handler, no hot reload, fresh server start. All kills are going to the user in slot 2 (a bot in my case).

```csharp
RegisterEventHandler<EventPlayerDeath>((@event, info) =>
{
    Server.PrintToChatAll("test");
    @event.Attacker = Utilities.GetPlayerFromSlot(2);
    return HookResult.Changed;
}, HookMode.Pre);
```
