### ISSUE TITLE
Feat: add team color

### ISSUE THREAD

**Issue by johnoclockdk** [roflmuffin/CounterStrikeSharp#161]
add team color base on what team the player are on at the time

**Comment by johnoclockdk** [comment]
> > add team color base on what team the player are on at the time
> 
> What does this mean? Team color for what? The color Hex or RGB?

that a silly question

but 
it take lightyellow for t and lightblue for ct. and put them into it own color name teamcolor

**Comment by roflmuffin** [comment]
[Example snippet](https://discord.com/channels/1160907911501991946/1175947333880524962/1209849943578116137) from @busheezy

Will be looking to add this to Chat Color extensions in the future.

```csharp
char GetChatColorByTeam(CsTeam team)
  {
    switch (team)
    {
      case CsTeam.None:
        return ChatColors.White;
      case CsTeam.Spectator:
        return ChatColors.LightPurple;
      case CsTeam.CounterTerrorist:
        return ChatColors.LightBlue;
      case CsTeam.Terrorist:
        return ChatColors.Yellow;
      default:
        throw new Exception("Invalid color.");
    }
  }
```
