### ISSUE TITLE
after new update some plugins arent loading

### ISSUE THREAD

**Issue by sidasltu** [roflmuffin/CounterStrikeSharp#169]
Hello after update example for me this important plugin stop working
12:02:23 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/K4-System/K4-System.dl

**Comment by mrc4tt** [comment]
As I have mentioned in the other issue you have created.

It is your GSP that has set a limit.
You need to get in touch with them.

The error was this:
```
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
```
My suspicion is that, based on the GSP he uses, `fs.inotify` is probably restricted by his gameserver provider

**Comment by sidasltu** [comment]
> As I have mentioned in the other issue you have created.
> 
> It is your GSP that has set a limit. You need to get in touch with them.
> 
> The error was this: `System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.`
> 
> My suspicion is that, based on the GSP he uses, `fs.inotify` is probably restricted by his gameserver provider

Ok i try to reach host support, thanks.

**Comment by roflmuffin** [comment]
You can also disable the plugin hot reload config option in `configs/core.json` which will disable hot reload but fix this error.

**Comment by matth2k** [comment]
@mrc4tt I have this same issue. I don't want to edit any sysctl parameters. Does something with `ulimit` work? That way I can set this per shell/job.

**Comment by mrc4tt** [comment]
> I have this same issue. I don't want to edit any sysctl parameters. Does something with `ulimit` work? That way I can set this per shell/job.


I don't have a problem with this on sysctl.conf: `fs.inotify.max_user_instances=524288` (I have never tested with `ulimit`, so I can't confirm about this)
