### ISSUE TITLE
admin no longer working

### ISSUE THREAD

**Issue by Ganji89420** [roflmuffin/CounterStrikeSharp#171]
after new update admin doesnt want to load.
try to use any !css_plugins or !css_admins_list and says i do not have permission.

**Comment by KillStr3aK** [comment]
> getting this error code ![Capture](https://private-user-images.githubusercontent.com/151049632/287545971-a4c3d7c2-92ec-4518-867e-dc71cc306342.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzQ2NDAsIm5iZiI6MTcwMTYzNDM0MCwicGF0aCI6Ii8xNTEwNDk2MzIvMjg3NTQ1OTcxLWE0YzNkN2MyLTkyZWMtNDUxOC04NjdlLWRjNzFjYzMwNjM0Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QyMDEyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmUxMjQyYjVmZTVlMWEyMmFlYzNhOWIxYjNlYmU4NGU3ODJjMWIxODM2MzBiY2M4MGVlYjFhMTBmYjMyY2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r9LygD3VAW25y25CGq4zfFe1wc0eL9xW-wPW0m7g600)

this seems to be related to the `TeamBet` plugin?

when you want to trigger a command in the chat you shouldn't include `css_` as prefix

**Comment by TheR00st3r** [comment]
We have the same problem with pugsharp.

var R00st3r = null;‎﹫T-Start: !creatematch
[CSS] You do not have the correct permissions to execute this command.

If the command is not recognized/misspelled there is no result.

**Comment by asapverneri** [comment]
I'm having this same issue with my windows cs2 server where i'm using daffyyyy's CS2-SimpleAdmin plugin.
It says that i don't have permission to use admin rights.

**Comment by roflmuffin** [comment]
Please try again on build 115 if you are using Windows.

**Comment by roflmuffin** [comment]
Thank @TheR00st3r it's their fix ❤️
