### ISSUE TITLE
Incorrect MaxPlayers definition

### ISSUE THREAD

**Issue by Poggicek** [roflmuffin/CounterStrikeSharp#184]
64 is not the gpGlobals->maxClients, it's the MAXPLAYERS which is the absolute limit of players for a mod (CS2/CSGO), it is used for static stuff like arrays. Reserved controller indexes go from 1 to (gpGlobals->maxClients + 1) not MAXPLAYERS. Iterating over 1 to MAXPLAYERS+1 will mean you're going to hit non-player indexes when the gpGlobals->maxClients is not actually set to 64. Voice Manager PR is already fixing this in unmanaged, however MaxPlayers in managed has to be properly fixed to pull the data from globalVars, ideally if it was cached and didn't call a native on every get.

**Comment by Poggicek** [comment]
GlobalVars should also be cached  and not retrieved on every access, cs2fixes does it in map start or so.

**Comment by Poggicek** [comment]
Perhaps GlobalVars as a whole could be exposed to managed

**Comment by roflmuffin** [comment]
We can look into exposing all of GlobalVars eventually, for now I've just added a native to replace the old maxplayers to improve correctness.
