### ISSUE TITLE
Feat: timer client params

### ISSUE THREAD

**Issue by johnoclockdk** [roflmuffin/CounterStrikeSharp#188]
allow the usage of client index on timers like sourcemod had it

```
CreateTimer(15.0, WelcomePlayer, client);

public Action WelcomePlayer(Handle timer, int client)
{
}
```

**Comment by KillStr3aK** [comment]
they are just timer parameters, also the code you have sent would be pretty unsafe to use even if it is a barebone example

**Comment by busheezy** [comment]
```csharp
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Core.Attributes.Registration;
using CounterStrikeSharp.API.Modules.Commands;

namespace HelloWorldPlugin;

public class HelloWorldPlugin : BasePlugin
{
  public override string ModuleName => "HelloWorld";
  public override string ModuleVersion => "0.1.0";

  [ConsoleCommand("timer_command", "This is an example command description")]
  public void OnTimerCommand(CCSPlayerController? player, CommandInfo command)
  {
    AddTimer(5, () =>
    {
      if (player == null || !player.IsValid)
      {
        return;
      }

      player.PrintToChat("Hello World!");
    });
  }
}
```

This isn't a thing as you can make sure your variables are in scope.

**Comment by johnoclockdk** [comment]
> ```cs
> using CounterStrikeSharp.API;
> using CounterStrikeSharp.API.Core;
> using CounterStrikeSharp.API.Core.Attributes.Registration;
> using CounterStrikeSharp.API.Modules.Commands;
> 
> namespace HelloWorldPlugin;
> 
> public class HelloWorldPlugin : BasePlugin
> {
>   public override string ModuleName => "HelloWorld";
>   public override string ModuleVersion => "0.1.0";
> 
>   [ConsoleCommand("timer_command", "This is an example command description")]
>   public void OnTimerCommand(CCSPlayerController? player, CommandInfo command)
>   {
>     AddTimer(5, () =>
>     {
>         if (player == null || !player.IsValid)
>         {
>           return;
>         }
> 
>         player.PrintToChat("Hello World!");
>     });
>   }
> }
> ```
> 
> This isn't a thing as you can make sure your variables are in scope.

that worked
