### ISSUE TITLE
commands not working in the game

### ISSUE THREAD

**Issue by BRUNOSCHUHh** [roflmuffin/CounterStrikeSharp#191]
My dedicated server is hosted on Linux, and the commands within the game are not working

admins.json

{
  "XXX": {
    "identity": "STEAM_0:0:XXXXXXXXX",
    "immunity": 100,
    "flags": [
      "@css/custom-flag-1",
      "@css/custom-flag-2"
      "@css/changemap"
      "@css/generic
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": true
    }
  },
  "Another erikj": {
    "identity": "STEAM_0:1:1",
    "flags": ["@mycustomplugin/admin"]
  }
}

**Comment by BRUNOSCHUHh** [comment]
my server has the latest version of counterstrikesharp
for Linux, permissions are added, for example the simpleadmin plugin which has the @css/changemap permission as shown above, however in-game I do not have access to the permission
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/e702379d-926b-4da9-844e-3df44fe2ddef)
It doesn't even work with @css/generic

flags in groups and id sitting correctly, if I'm doing something wrong please help me
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/b80dacd3-4e9f-49cf-bf28-162cd3e05c2b)
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/35b9d952-c7a6-4960-83e3-a23f28d05ae6)

**Comment by asdfxD** [comment]
"identity": "STEAM_0:0:XXXXXXXXX",

Use STEAMID64

76561197966******

**Comment by crashzk** [comment]
You need a plugin to change the map etc.

The flags are just for plugins to use as a reference, leave something centralized, @roflmuffin can explain it better.

In short, the flags you configured only give access to the commands, but you need a plugin to change the map and other flags you configured.

https://docs.cssharp.dev/docs/admin-framework/defining-admins.html
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/32937653/c3af2f7a-cedc-455f-9b15-ca282c726d9b)

**Comment by roflmuffin** [comment]
Remove the `.example` suffix from your files. It should be `admins.json` and `admins_groups.json` once you modify the files. The files shipped with CS# are just example files.
