### ISSUE TITLE
Problem with respawn() method.

### ISSUE THREAD

**Issue by zoxile** [roflmuffin/CounterStrikeSharp#192]
I cannot respawn anyone anytime like I want. After respawning them near the round start 1 or 2 times I can no longer respawn anyone, it seems to be a limiter. How can I solve this?

**Comment by roflmuffin** [comment]
We are calling the valve function under the hood, so there is probably a limitation inside their method.

**Comment by zoxile** [comment]
> We are calling the valve function under the hood, so there is probably a limitation inside their method.

Is there anything to bypass this?

**Comment by roflmuffin** [comment]
> > We are calling the valve function under the hood, so there is probably a limitation inside their method.
> 
> Is there anything to bypass this?

Reverse engineer a better method

**Comment by oylsister** [comment]
manual respawn from cs2fixes. https://github.com/Source2ZE/CS2Fixes/commit/ac0d60303c62aa13bb700480c59be603c2eb773f

**Comment by oylsister** [comment]
I know this is already closed, But I gonna show you how it can be done.

```cs
CBasePlayerController_SetPawnFunc.Invoke(client, clientPawn, true, false);
VirtualFunction.CreateVoid<CCSPlayerController>(client.Handle, GameData.GetOffset("CCSPlayerController_Respawn"))(client);
```

**Comment by UgurhanK** [comment]
> I know this is already closed, But I gonna show you how it can be done.
> 
> ```cs
> MemoryFunctionVoid<CCSPlayerController, CCSPlayerPawn, bool, bool> CBasePlayerController_SetPawnFunc = new(GameData.GetSignature("CBasePlayerController_SetPawn"));
> CBasePlayerController_SetPawnFunc.Invoke(client, clientPawn, true, false);
> VirtualFunction.CreateVoid<CCSPlayerController>(client.Handle, GameData.GetOffset("CCSPlayerController_Respawn"))(client);
> ```
> 
> Signature
> 
> ```json
> "CBasePlayerController_SetPawn": {
>     "signatures": {
>         "library": "server",
>         "windows": "\\x44\\x88\\x4C\\x24\\x2A\\x55\\x57",
>         "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xFC\\x53\\x48\\x89\\xF3\\x48\\x81\\xEC\\xC8\\x00\\x00\\x00"
>     }
> }
> ```

can u give an example. i used it in my command but server crashed.
