### ISSUE TITLE
Can I get any help installing a teleport feature?

### ISSUE THREAD

**Issue by donjells** [roflmuffin/CounterStrikeSharp#195]
Is there any teleport feature for KZ maps that works with CS Sharp?

I'd really appreciate the help since I just payed a month of dat host to host a KZ server although without any plugins this kind of defeats the purpose of a KZ server. I'd like to have a timer and teleport commands. 

Anyone know about this?

Thanks so much !!!

**Comment by KillStr3aK** [comment]
this is unrelated to cssharp

**Comment by roflmuffin** [comment]
Please only raise issues on Github for bugs/feature requests for CS#. I would recommend viewing the plugin releases channel in discord if there are any relevant plugins: https://discord.gg/eAZU3guKWU

**Comment by donjells** [comment]
I understand, Thank you
