### ISSUE TITLE
EventPlayerShoot don't work

### ISSUE THREAD

**Issue by OsuDesu** [roflmuffin/CounterStrikeSharp#196]
public override void Load(bool hotReload) { 
        base.Load(hotReload);
        RegisterEventHandler<EventPlayerShoot>((@event, info) => {
                 Server.PrintToChatAll($"{@event.Userid.PlayerName}");
                 return HookResult.Continue;
        });
    }

this hook doesn't work

**Comment by roflmuffin** [comment]
EventPlayerShoot does not appear to be being fired by Valve anymore, you can search `EventPlayerShoot` on discord for more context.

**Comment by xtance** [comment]
For anyone searching for this: `EventWeaponFire` still works :)
