### ISSUE TITLE
Code causes server crash during startup

### ISSUE THREAD

**Issue by NotJustin** [roflmuffin/CounterStrikeSharp#197]
If the following plugin is in the plugins folder during server startup, the server crashes when attempting to load this plugin.
No issue if loading it after startup.

I tested using Utilities.GetPlayers(), but it seems to be related specifically to GetEntityFromIndex.
```c#
using CounterStrikeSharp.API.Core;

namespace Test;
public class Test : BasePlugin
{
    public override string ModuleName => "";
    public override string ModuleVersion => "";
    public override void Load(bool hotReload)
    {
        Utilities.GetPlayers();
    }
}

**Comment by KillStr3aK** [comment]
probably the entity system is not yet initialized that time as using this code with checking hotreload should be fine (assuming that the system has initialized)

**Comment by Hackmastr** [comment]
> probably the entity system is not yet initialized that time as using this code with checking hotreload should be fine (assuming that the system has initialized)

In hot reload it's actually fine. The issue is on server boot when no ents are init yet.

You can solve it by adding a timer.

**Comment by NotJustin** [comment]
> probably the entity system is not yet initialized that time
> The issue is on server boot when no ents are init yet.
Let's call this a test case for accessing the entity system before it is initialized.

Does it make sense for this to crash? Should it not just fail plugin load with an error like: "Cannot access entity system utils before entity system is initialized"?

> You can solve it by adding a timer.

Maybe a forward would be better to indicate when these utilities are safe to use, if one doesn't exist?

If this is a CS2 issue and not a counterstrikesharp issue, or if these suggestions are otherwise not possible then my apologies.

**Comment by roflmuffin** [comment]
CSS load is called even if you started the server without a map. Entities are only safe to use once a map is loaded, so you could just listen to mapstart forward/listener. Ideally yes it shouldn't crash but it's not super high priority to add safeguards around this since it's unlikely to make it into a production plugin anyways

**Comment by NotJustin** [comment]
> Entities are only safe to use once a map is loaded.

That knowledge is good enough of a solution for me. Closing as resolved.
