### ISSUE TITLE
your client is out of date

### ISSUE THREAD

**Issue by IRedbrine** [roflmuffin/CounterStrikeSharp#203]
i give the your client is out of date message wen try open server after 126 update (Only runtime version)

**Comment by destoer** [comment]
This might be silly but did you update the server itself in steamcmd?

**Comment by johnoclockdk** [comment]
this issue with with ya client/server not the CounterStrikeSharp project

**Comment by KillStr3aK** [comment]
this is not related to cssharp

**Comment by roflmuffin** [comment]
Server/Client mismatch, unrelated to CS#
