### ISSUE TITLE
Admin permissions not working 

### ISSUE THREAD

**Issue by BRUNOSCHUHh** [roflmuffin/CounterStrikeSharp#207]
I added the commands and it's giving me this message, I need help

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/1ce341a1-2b02-446c-ab44-e777e52a9735)
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/ad560056-4288-4e2f-b046-d08ee1c08a6d)
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/4ebd12f7-9db0-4121-87fd-818a712378d4)

**Comment by mayersgamer** [comment]
i think you need an admin plugin to install , cs sharp didnt inclusde admin settings 

https://github.com/Hackmastr/css-basic-admin

**Comment by BRUNOSCHUHh** [comment]
> i think you need an admin plugin to install , cs sharp didnt inclusde admin settings
> 
> https://github.com/Hackmastr/css-basic-admin

I forgot to comment, but I'm using this plugin.
https://github.com/daffyyyy/CS2-SimpleAdmin

**Comment by BRUNOSCHUHh** [comment]
I just tested with another InfoPlayers plugin where the permission is @css/generic, adding the permission gives the same message.


![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/153410845/8923c6d7-f87a-4129-b297-80a366ec318f)

**Comment by roflmuffin** [comment]
Can you try again with v132, also confirming there are no example suffixes on any files?

**Comment by dzcamrn** [comment]
I'm having the same issue on build 141

**Comment by penderes** [comment]
Same issue here, I'm running Build 142:
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/17273181/fd655d2e-017a-4891-b711-a893532e17d9)
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/17273181/64394cb2-94d7-452b-9203-87b2dbbf4578)

**Comment by roflmuffin** [comment]
Please confirm using `css_admins_list` command and that the steam server is not having an authorisation delay.

**Comment by derkalle4** [comment]
FYI: for everyone that has the same error: please look into the server log. The JSON file needs to be valid. Otherwise it will be ignored. Quick check would be the server commands (from the server console):

css_admins_list
css_groups_list

If either of these is empty but you have configured them in the json files you have an error in your syntax. Use an online json validator or check the beginning of the server log (search for admin to find it easily).
