### ISSUE TITLE
scripting/listeners missing previously implemented listener yaml

### ISSUE THREAD

**Issue by KillStr3aK** [roflmuffin/CounterStrikeSharp#21]
Listeners implemented in #16 have no .yaml file currently.

I'll put them in 'server.yaml' when I get home.

**Comment by roflmuffin** [comment]
All good, I think we can honestly do away with the listeners yaml files anyway, there aren't enough that they need to be generated, and they aren't validated against them anyway. Better to be able to handwrite them and add comments.

**Comment by KillStr3aK** [comment]
Its all good in general but I dont think we should leave them just because we dont have too much of them currently and they can be handwritten instead of generated, I'd add summary to generated listeners just like to handwritten, the difference is the fact that I'd only have to write the summary.

Also, the summary should be included with the core so intellisense could display the documentation in the IDE, is it something that we should support, or leave the docs on their page (I mean ofc we have the web docs but also the IDE docs)
