### ISSUE TITLE
Picking up hostage causes entity corruption

### ISSUE THREAD

**Issue by switz** [roflmuffin/CounterStrikeSharp#212]
Here is a minimal reproduction: https://gist.github.com/switz/c398f288f20a5b2955ba2d8bd8b0827b

If you compile the plugin above and start a match on a hostage map

pick up a hostage and then kill the sole enemy bot (thereby ending the round) the whole server crashes from accessing an existing `CCSTeam` entity. it does not crash from accessing it's schema values, rather just touching the entity variable itself, which makes this harder to debug.

More details are in this thread: https://discord.com/channels/1160907911501991946/1183648718013071390

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/990166/63f81e99-d5fb-413c-a4f3-2d1e02b35fc8)

**Comment by Poggicek** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/45881722/27dd0908-324d-4240-9290-924309f4918c)
On round end where it loops through all entities, it ends up on hostage carrier prop that has a null DesignerName. This crashes inside the FindAllEntitiesByDesignerName code.

**Comment by roflmuffin** [comment]
The repro code did not crash the server for me on Windows, but I did get the null reference error as Poggie outlined above, I've added a null check to designer name for this method and the repro plugin worked for me now.

**Comment by switz** [comment]
thank you!
