### ISSUE TITLE
Another plugin can't work after instal CSSharp..

### ISSUE THREAD

**Issue by denrio157** [roflmuffin/CounterStrikeSharp#219]
Hello can you help me? what is wrong with me? I'm trying install CSSharp and after installed my another plugin can't work like "CS2SCRIM"

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/31591836/f0682e88-8e30-4dce-8674-adb0381b121b)

**Comment by ady2324** [comment]
since [v136]
some plugins dosen't work
so i stay with wersion v135
