### ISSUE TITLE
[Command Listeners] Listening to certain sv_cheat commands

### ISSUE THREAD

**Issue by ManifestManah** [roflmuffin/CounterStrikeSharp#22]
After experimenting a fair bit with command listeners earlier today, I think I might have stumbled upon a bug.
I was able to tap in to commands such as the jointeam, and meta commands and the likes.

I found that I was unable to track when the "kill" and "explode" commands were being used, and I suspect it is because it requires sv_cheats 1 to be enabled in order to use these two commands. But despite enabling sv_cheats, I could use the commands, but the command listener did not seem to register the use of them.
The code compiled just fine, and no errors were to be found in the console when the two commands were used.

This is what I had in my load function:
```c#
        AddCommandListener("kill", CommandListener_Kill);
        AddCommandListener("explode", CommandListener_Kill);
```

This is what I had outside of my load function, within the main / base class:
```
    private HookResult CommandListener_Kill(CCSPlayerController? player, CommandInfo info)
    {
        Console.WriteLine("Debug - Listener kill / explode");

        // If the the CCSPlayerController entity is invalid then execute this section
        if (!player.IsValid)
        {
            return HookResult.Continue;
        }

        // If the pawn associated with the CCSPlayerController is invalid then execute this section
        if (!player.PlayerPawn.IsValid)
        {
            return HookResult.Continue;
        }

        Server.PrintToChatAll("The kill / explode commands are blocked");

        return HookResult.Stop;
    }
```

**Comment by KevinllBin** [comment]
the same to u
