### ISSUE TITLE
TerminateRound missing arguments on windows, causing the register shift to somewhere else

### ISSUE THREAD

**Issue by Yarukon** [roflmuffin/CounterStrikeSharp#226]
in IDA, the function looks like this
![Snipaste_2023-12-26_19-21-29](https://github.com/roflmuffin/CounterStrikeSharp/assets/61296195/f28b1b18-4498-4a39-8440-4196d4230b8c)
a4 and a5 can just pass in 0
currently the cssharp's implementation makes the delay just dont work
down below is my implementation
```C#
public delegate void TerminateRoundFn(nint g_Gamerules, float fDelay, uint iReason, nint a4, byte a5);
```

**Comment by KillStr3aK** [comment]
delay works for terminateround

**Comment by Yarukon** [comment]
> delay works for terminateround

weird, i tested on windows, the delay doesnt work, sometimes it will crash the server

**Comment by Yarukon** [comment]
TerminateRound: unknown round end ID 1084227584
clearly the register get offset to some random place

**Comment by Yarukon** [comment]
```C#
Utilities.FindAllEntitiesByDesignerName<CCSGameRulesProxy>("cs_gamerules").First().GameRules.TerminateRound(5f, RoundEndReason.RoundDraw);
```
this is my test code

**Comment by M1kep** [comment]
Can confirm this crashes...

It looks like CCSGameRules::AddTeamAccount was inlined into CCSGameRules::RoundWon, and the extra two values seem to be related to which team won, but I can't quite figure it out :/
