### ISSUE TITLE
https://docs.cssharp.dev/ is unavailable in Quebec

### ISSUE THREAD

**Issue by yonilerner** [roflmuffin/CounterStrikeSharp#230]
Just thought youd like to know

**Comment by rothadamcz** [comment]
Not anymore. At least not for me.

**Comment by yonilerner** [comment]
Fascinating. I wonder if its because of my location? 

I am currently in Quebec, Canada, but if I VPN into the US I can access the website just fine

**Comment by yonilerner** [comment]
No its not that. If I VPN into Canada it also works.

If I try to connect without VPN, the error I get is ERR_SSL_PROTOCOL_ERROR

**Comment by rothadamcz** [comment]
It may have something to do with your ISP

**Comment by rothadamcz** [comment]
You can also try different browser
