### ISSUE TITLE
CoreConfig file not found

### ISSUE THREAD

**Issue by ppokrywka32** [roflmuffin/CounterStrikeSharp#232]
After upload plugin and start server give warning and the file is not creating: (i was checking version 141 and 135)

[10:01:53.447] CSSharp: CoreConfig file not found, creating one from example.
[10:01:53.447] CSSharp: CoreConfig file not found, creating one from example.
[10:01:53.447] CSSharp: CoreConfig file not found, creating one from example.
[10:01:53.447] CSSharp: CoreConfig file not found, creating one from example.
Segmentation fault (core dumped)

**Comment by t2elzeth** [comment]
> check your host directory file permissions

You saved me, thank you so much! 

In my case SFTP connection was under a root user, while server files were owned by "steam" user. That's why after transferring "addons" folder, it was owned by root, not steam.

**Comment by Kazukira** [comment]
Please tell me exactly how you solved the problem?

**Comment by betulgundogdu** [comment]
> Please tell me exactly how you solved the problem?

Hi, I faced the same issue. In my case, my server was running on Docker, and when I edited the gameinfo.gi file, its owner changed to root. However, entire home folder were owned by steam. So, I changed the owner of the home folder recursively to steam, and this fixed the issue.

If your server is on Linux, you can check the file owner using the command `ls -l /path/to/folder`. You can change the owner recursively with the `chown -R username /path/to/addons` command.

I’m not sure if this is the best solution, but it worked for me.
