### ISSUE TITLE
Mysql/curl/wget support?

### ISSUE THREAD

**Issue by Pok4** [roflmuffin/CounterStrikeSharp#240]
Hi,
Im new with cs sharp.. Does the framework support mysql,curl or wget?
Can i write custom content to files in specific folder with a plugin?
Please,give me examples.
Thanks.

**Comment by M1kep** [comment]
From what I've seen, you'll need to bring your own library for DB stuff at least. See https://github.com/roflmuffin/CounterStrikeSharp/blob/main/examples/WithDatabaseDapper/WithDatabaseDapperPlugin.cs for an example of using SQLite.(The other examples may have some useful things as well)

The above example also uses the ModuleDirectory for the SQLite file, which you can probably adapt for your own file needs.

**Comment by KillStr3aK** [comment]
This is not something that should be supported by the core itself as you can use any nuget package on your own so you are fine as long as there is an available implementation already
