### ISSUE TITLE
can you help me 

### ISSUE THREAD

**Issue by mayersgamer** [roflmuffin/CounterStrikeSharp#244]
STEAM_0:0:795510228
STEAM_0:1:68620657

already installed simple admin plugin for admin managment , but i cant seem to make it work 

if i add one id it works ,i can control my server , but if i try to add another admin , both will not be admin , and server says that i need @generic to acces the command i type 

can you give me an example using this 2 steam id ?

i was managing csgo servers for years but its first time i feel helpless i cant even add an admin .

**Comment by KillStr3aK** [comment]
maybe show the configuration you have tried as it could be a little typo, or if it is not set in the built in system then its pretty much plugin related and you can ask for support in the proper places instead

**Comment by mayersgamer** [comment]
its been happning with 2 plugins , check this if its true 👍 

{
  "admin1": {
    "identity": "STEAM_0:0:795510228",
    "flags": ["@css/changemap", "@css/generic"]
  },
  "admin2": {
    "identity": "STEAM_0:1:68620657",
    "flags": ["@css/root"]
  }
}

**Comment by xLeviNx** [comment]
May just be related to the steam auth being delayed
