### ISSUE TITLE
WeaponServices identifies MP5 as MP7

### ISSUE THREAD

**Issue by yonilerner** [roflmuffin/CounterStrikeSharp#247]
My player has an MP5 equipped, but the` CCSPlayerController#PlayerPawn#WeaponServices#MyWeapons` thinks that it's an MP7. And if I actually have an MP7 it is correctly identified as an MP7. The purchase event also correctly identifies it as an MP5. It's just the WeaponServices that thinks it's an MP7 as far as I can tell. I can't find any other weapons where this is happening.

**Comment by oylsister** [comment]
you can check these with ItemDefinition

**Comment by oylsister** [comment]
```csharp
var weapons = client!.PlayerPawn.Value!.WeaponServices!.MyWeapons;

foreach (var weapon in weapons)
{
    var itemdef = (ItemDefinition)weapon.Value.AttributeManager.Item.ItemDefinitionIndex;

    if(itemdef == ItemDefinition.MP5_SD)
    {
        client.PrintToChat("this is mp5sd");
    }
}
```

**Comment by yonilerner** [comment]
Oh cool thank you!

**Comment by roflmuffin** [comment]
Closing this, cs# has no way of knowing this based on the class name, but it can be checked with item definition as outlined
