### ISSUE TITLE
admin missing permissions when running commands on server

### ISSUE THREAD

**Issue by lostsoul6** [roflmuffin/CounterStrikeSharp#248]
Hello There ,

I'm running a CS2 server on Ubuntu 22 and I'm using CS2-SimpleAdmin plugin by daffyyyy . I have added an admin using the following command : 

css_addadmin ""7656119XXXXXXXXX" "Mr. Reese" "#css/admin" 100 0

admin is added in the database . look at the picture : 

![phpadmin](https://github.com/roflmuffin/CounterStrikeSharp/assets/127633547/c757ce40-8008-437f-b7e3-b96f616c164b)

when going into the game and typing !admin in the chat , it says I miss @css/generic permissions . see the pic below : 

![admin-issue](https://github.com/roflmuffin/CounterStrikeSharp/assets/127633547/843e44e9-65d8-47da-b9c4-1a011008313e)

I have been seaching for days without luck . it seems it's not plugin related . maybe my counterstrikesharp settings are wrong?

when running " css_admins_list "  on console , I can see the admin and its rights . the pic below shows that : 

![console](https://github.com/roflmuffin/CounterStrikeSharp/assets/127633547/678aafa9-2411-4a60-bc7c-f784f13605b9)

This is my css admins.json : 

```
{
  "Mr. Reese": {
    "identity": "765611XXXXXXX7X1",
    "immunity": 100,
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  },
  "Another erikj": {
    "identity": "STEAM_0:1:1",
    "flags": ["@mycustomplugin/admin"]
  }
}
```

this is my admin_groups.json : 

```
{
  "#css/admin": {
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "immunity": 100
  }
}
```

this is my admin_overrides.json :  

```
{
  "example_command": {
    "flags": [
      "@css/custom-permission"
    ],
    "check_type": "all",
    "enabled": true
  }
}
```

and this is my core.json :  

```
{
    "PublicChatTrigger": [ "!" ],
    "SilentChatTrigger": [ "/" ],
    "FollowCS2ServerGuidelines": false,
    "PluginHotReloadEnabled": true,
    "ServerLanguage": "en"
}
```

I'd be really thankful is anyone can help me understand what is wrong . It's funny the server is fully setup and ready yet I can't add an admin for the life of me !

**Comment by criskkky** [comment]
Hi @lostsoul6,

I suspect that the most recent version of CounterStrikeSharp is causing a delay in validating Steam UserIDs. It happened to me, but I can't confirm if it's a widespread issue.

**To identify the problem:**

1. Join to your server with the latest CSS version.
2. Attempt admin commands.
3. If admin commands doesn't work, check the console and search for something like:
```
SV: "yourname<ID><[U:1:NUMBERS]><>" STEAM USERID validated
```
4. If it doesn't appear, wait for 1 or 2 minutes, and it should eventually show up.
5. After "STEAM USERID validated," try admin commands again. If they work now, we can confirm that the issue is related to Steam User ID validation delay.

**Comment by lostsoul6** [comment]
@criskkky Hi my friend ,

Yes , that's exactly the issue . My admin commands worked after a while . I thought that's a Steam issue . Didn't know it was related to CSS . Will we get an update to fix it?

**Comment by criskkky** [comment]
@lostsoul6 Now that we confirmed the issue, must wait the answer from @roflmuffin.

**Comment by criskkky** [comment]
@lostsoul6 As a temp solution you could rollback to CounterStrikeSharp version 1.4.2, that worked perfect to me.

**Comment by lostsoul6** [comment]
@criskkky I'm not on a production server . I will probably wait and see if @roflmuffin confirms there is such problem . If there is , I will wait for an update but if not , I will downgrade to previous versions one by one to see if they fix my problem .

**Comment by lostsoul6** [comment]
@criskkky do you have any updates on the delayed steam validation issue? I haven't tested the new version to see if it has solved the issue .

**Comment by criskkky** [comment]
@lostsoul6, I haven't tested lastest version, don't wanna take the risk xD if you do it tell me how it's going

**Comment by daffyyyy** [comment]
> @lostsoul6 fixed

Its not fixed but issue are related to steam not css.
I fixed this by load admin permissions on map start not on client auth in plugin.

**Comment by roflmuffin** [comment]
Yeah the authorised steam ID is set after valve confirms it is legit on their side (not spoofed), until then the admin permissions will be missing for that user
