### ISSUE TITLE
Question: How to write a message to the client's dev console and/or the in-game chat?

### ISSUE THREAD

**Issue by miguno** [roflmuffin/CounterStrikeSharp#25]
Background: I created a custom command `plugin_info`, and clients (once connected to the server) can successfully run that command when they open the in-game console.

Question 1: How can I write a response message back to the client so it shows up in their CS2 developer console?

What I want is something like this:

```
# Client opens developer console

> plugin_info
Plugin version: 1.2.3.4
```

With `Console.Writeln()`, which is what the custom command currently uses, the output is (obviously) written to the server's log/console, but not back to the client. I have dug through the CounterStrikeSharp API but have not found what I was looking for.

Question 2: Are there equivalent methods for CS2's console commands `say` and `say_team`?  Or is there a way to run CS2's built-in console commands via CounterStrikeSharp? Here, it's about sending messages from the server to the in-game chat.

Edit: I did find `Server.PrintToChatAll()` to print a message to all players in the in-game chat.

**Comment by KillStr3aK** [comment]
Check #17

**Comment by miguno** [comment]
Thanks!  For others who might come across this:

```csharp
    [ConsoleCommand("plugin_info", "Print version and additional information about the plugin")]
    public void OnCommand(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null) {
            // Command was called by the server, not by a player
            Console.WriteLine($"[SERVER] {this.ModuleName}: version {this.ModuleVersion}");
            return;
        }

        // Prints to the player's console.
        player.PrintToConsole($"[player.PrintToConsole] {this.ModuleName}: version {this.ModuleVersion}");

        // Prints to the server's console, but NOT to the player's console.
        Server.PrintToConsole($"[Server.PrintToConsole] {this.ModuleName}: version {this.ModuleVersion}");

        // Prints to in-game chat.
        Server.PrintToChatAll($"[Server.PrintToChatAll] {this.ModuleName}: version {this.ModuleVersion}");
        Server.PrintToChatAll($"Welcome, {player.PlayerName}!");

        // Prints to STDOUT of the server's process.
        Console.WriteLine($"{this.ModuleName}: version {this.ModuleVersion}");
    }
```
