### ISSUE TITLE
[Improvement] Load/Unload Plugins

### ISSUE THREAD

**Issue by criskkky** [roflmuffin/CounterStrikeSharp#252]
> [!Note]
> I don't know if it happens only with this plugin.
> Running API Version: 142

Hi, currently to load plugins we must use filename, for example:

> If file is "NoBlock.dll".
`css_plugins load NoBlock` ✔
And it's pretty easier to load any plugin, I like this way.

But for plugin unload we must use the plugin name, we can't use filename.
> If plugin name is "[Custom] No Block".
`css_plugins unload "[Custom] No Block"` ✔
> Trying unload using filename doesn't work.
`css_plugins unload NoBlock` ❌

**Here's an image testing all ways explained.**
![Screenshot_1](https://github.com/roflmuffin/CounterStrikeSharp/assets/36176343/c67ce485-15e3-4089-9bff-92fb3adb779f)

That could be annoying.
So, thinking that's not possible to have same named .dll files, could we have only the "filename way" to load and unload plugins?.

I'm sorry if I overlooked something proposing this logic. If that's the case I would appreciate explanations as to why it shouldn't work like I proposed.

**Comment by audiomaster99** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/116572799/cea7c124-840a-478c-8fe8-01eed7c5e1f4)
?

**Comment by criskkky** [comment]
> @audiomaster99:
> ![image](https://private-user-images.githubusercontent.com/116572799/296286081-cea7c124-840a-478c-8fe8-01eed7c5e1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwODEwNzgsIm5iZiI6MTcwNTA4MDc3OCwicGF0aCI6Ii8xMTY1NzI3OTkvMjk2Mjg2MDgxLWNlYTdjMTI0LTg0MGEtNDc4Yy04ZmU4LTAxZWVkN2M1ZTFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxNzMyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzIxNDJkMjA2ZDU4MDQzNDJmMGU4ZGM3NWZiZmM4NTE1Zjg4MzZhOGU2YzQ0MzJmZTBmNjI2ZjY0Y2VlY2E3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B3M4OxCKC22Et0tvku44kGWr_x7tkhA4NadLCz53aoo)
> ?

This happens when the plugin has the same name as filename.dll and it's a decision that the plugin author may not always choose.
