### ISSUE TITLE
I need help, man.

### ISSUE THREAD

**Issue by Nianmou** [roflmuffin/CounterStrikeSharp#254]
Bro, I'm trying to modify the BOT's field of view orientation to look ahead for the purpose of meeting an enemy to turn on the shooting, but I can't seem to find anything like that!

**Comment by B3none** [comment]
If you want support you should write a message in the discord server: https://discord.gg/ZMMaFPYXCa

**Comment by willjsaint** [comment]
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive/Bot_Behavior_Trees
