### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by chycken** [roflmuffin/CounterStrikeSharp#262]
![aaa](https://github.com/roflmuffin/CounterStrikeSharp/assets/25958225/6f3c0488-c871-49ea-85d0-a0483c307e3f)

Hello, im getting this on console (picture attached) , and a lot of plugins aint loading:
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Can you help me? using latest cssharp (v147) (módosítva)

**Comment by chycken** [comment]
Reinstalled dotnet folder and working :D

**Comment by matth2k** [comment]
I fixed this by editing my `csproj` to explicitly use version 8.0: `<TargetFramework>net8.0</TargetFramework>`
