### ISSUE TITLE
Assertion failed in option setup model error

### ISSUE THREAD

**Issue by lostsoul6** [roflmuffin/CounterStrikeSharp#270]
Hello Guys ,

After updating to the latest version , I'm getting the following error in console constantly :

![assertation-failed](https://github.com/roflmuffin/CounterStrikeSharp/assets/127633547/ab0df4b7-53b7-40d0-8a51-92a606eeb82f)

Is it related to CSS or something else broke after updating CSS?

**Comment by B3none** [comment]
Release `v148` was a minor C# code change so I highly doubt it's related to this.

**Comment by lostsoul6** [comment]
@B3none I updated from v142 to v148 . I reverted back to v142 but problem still exists so the issue is not with CSS . I recently installed CS2-Parachute and ResourcePreCacher plugins so probably one of these is causing the issue . The error in the first line of the following picture is about something being wrong with API .

![error-asli](https://github.com/roflmuffin/CounterStrikeSharp/assets/127633547/533232e5-ac06-4d9c-ab16-e6a269619c48)

**Comment by B3none** [comment]
I'd suggest asking in the Discord server for help with this. There's a link to the Discord server at the top of the CounterStrikeSharp documentation.

As this is unrelated to this repo I'm going to close this ticket now 👍
