### ISSUE TITLE
unknown command css_plugins

### ISSUE THREAD

**Issue by gan3o** [roflmuffin/CounterStrikeSharp#273]
i installed latest counterstrikesharp but plugin error on meta list. How to fix this?

meta list
Listing 1 plugin:
  [01] <ERROR>
css_plugins
Unknown command 'css_plugins'!

**Comment by gan3o** [comment]
![css](https://github.com/roflmuffin/CounterStrikeSharp/assets/157226227/60a8a6cf-2c49-4aac-aa5d-32461b3d7f37)
![meta](https://github.com/roflmuffin/CounterStrikeSharp/assets/157226227/ba32f76a-5145-4463-8b6f-684557dbc9e5)

**Comment by crashzk** [comment]
Does this error only occur on Windows!? Running on Linux servers here and everything is fine when using the command in the server console.

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/32937653/8cfe5af5-7bad-4dec-873c-37403650da99)

**Comment by audiomaster99** [comment]
> ![css](https://private-user-images.githubusercontent.com/157226227/298349474-60a8a6cf-2c49-4aac-aa5d-32461b3d7f37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjI0ODYsIm5iZiI6MTcwNTk2MjE4NiwicGF0aCI6Ii8xNTcyMjYyMjcvMjk4MzQ5NDc0LTYwYThhNmNmLTJjNDktNGFhYy1hYTVkLTMyNDYxYjNkN2YzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQyMjIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzIzMjg3M2I5MDY2NjNjODdlZmYxOTVjYjQ0MTM2OGY4NDE5ZDA5ZmUyZDcwY2M1YWQ1NTNlYTU3N2E0Y2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6mm3w3KehqrSA6E8MdrDjD2iOwyx7Wh9U40CDcseiGQ) ![meta](https://private-user-images.githubusercontent.com/157226227/298349488-ba32f76a-5145-4463-8b6f-684557dbc9e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjI0ODYsIm5iZiI6MTcwNTk2MjE4NiwicGF0aCI6Ii8xNTcyMjYyMjcvMjk4MzQ5NDg4LWJhMzJmNzZhLTUxNDUtNDQ2My04YjZmLTY4NDU1N2RiYzllNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQyMjIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2Q3ZDBhOGEwYWMyNDVlNzQ5ZmQ5ZDg2OTE2ZWY1OTcwYTJjZTkyMjBmNTE4NDAxMTBmYjAyYmE2NTExZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FWT4W5DtkqXltQaXpAtwhbPOHKCjJEV-xE9V4qauPCA)

cs# is not loaded, your issue is not css_plugins command but counterstrike sharp not loading, make sure you downloaded version thats right for your os, and version with runtime if its your first time installing cs#

**Comment by characharm** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/123120856/59cfc7b2-ca77-4e8d-a276-d96320ad9ac3)
