### ISSUE TITLE
Support NativeAOT plugin?

### ISSUE THREAD

**Issue by stevefan1999-personal** [roflmuffin/CounterStrikeSharp#275]
I did not mean the metamod plugin itself but the downstream plugins should they be working with NativeAOT?

**Comment by KillStr3aK** [comment]
if I recall correctly the plugin loader that is being used in the project supports nativeaot but I'm not 100% sure about this, in general its not something that should be supported in my opinion

**Comment by roflmuffin** [comment]
We do not plan on supporting NativeAOT plugins at this stage
