### ISSUE TITLE
Is there any option in CSS to reserve slots for admins?

### ISSUE THREAD

**Issue by lostsoul6** [roflmuffin/CounterStrikeSharp#283]
Hello There ,

Today for the first time I saw my server was full player 18/18 and I couldn't join the server . I use mini-admin plugin but I didn't see any option there to reserve slots for admins . Is it possible to do so with CSS? I want it in a way that server can be full 18/18 but when admin wants to join , someone is kicked so that he can join .

**Comment by crashzk** [comment]
It would be possible to make a plugin in CSSharp, but for that you need a developer to do it. GitHub issues are for problems in CSSharp itself.

Plugin requests use discord and try there, someone can help you with this.

https://discord.gg/eAZU3guKWU

**Comment by mayersgamer** [comment]
that plugin already exist search the name : reserved slots
