### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by ssypchenko** [roflmuffin/CounterStrikeSharp#285]
Unfortunately, localization does not work for me. 

Here is the plugin code:

`using System;
using System.IO;
using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Core.Attributes.Registration;
using CounterStrikeSharp.API.Core.Translations;
using CounterStrikeSharp.API.Modules.Commands;

namespace TestPlugin
{
    public class TestPlugin : BasePlugin
    {   
        public override string ModuleName => "Test Plugin";
        public override string ModuleVersion => "v1.0.0";
        public override void Load(bool hotReload)
        {
            Console.WriteLine($"Test started");      
        }
        [ConsoleCommand("test", "Test command")]
        public void OnTestDCCommand(CCSPlayerController? playerController, CommandInfo command)
        {
            if (playerController != null)
            {
                playerController.PrintToChat(Localizer["test.translation"]);
            }
        }
    }
} `

Here is the localization file:

en.json
`{
  "test.translation": "This is the english text"
} `

ru.json and fr.json are similar with the translated text.

In case any language is set in CS2, !test command prints the text in English "This is the english text"
Attached is an archive with the plugin code.

[TestPlugin.zip](https://github.com/roflmuffin/CounterStrikeSharp/files/14022679/TestPlugin.zip)

**Comment by frederikstonge** [comment]
Right now, client language is not supported. You need to set the language at the server level.
