### ISSUE TITLE
CPlayer_MovementServices And CCSPlayer_MovementServices

### ISSUE THREAD

**Issue by Nianmou** [roflmuffin/CounterStrikeSharp#291]
CCSPlayer_MovementServices,CPlayer_MovementServices Is it possible to control the player, or BOT to move to the left, or right?Is there anything similar that can control the movement of the Bot? criptedMoveTo_t？

**Comment by Nianmou** [comment]
Is there any other way to specify a particular individual human machine?

**Comment by roflmuffin** [comment]
I'd advise taking this kind of question to the #plugin-dev channel on the Discord as this lays outside the scope of a core issue/feature request at this stage.
