### ISSUE TITLE
Setting a player to Spectator returns invalid teamid

### ISSUE THREAD

**Issue by flabbert** [roflmuffin/CounterStrikeSharp#293]
I want to set a newly connected player to spectator if they are not assigned to team.

`CsTeam.Spectator` is set as 1, but when using `.SwitchTeam(1)`

Server responds with: 
`CCSPlayerPawnBase::SwitchTeam( 1 ) - invalid team index.`

**Comment by B3none** [comment]
Are you after `ChangeTeam(CsTeam.Spectator)` instead?

**Comment by flabbert** [comment]
`ChangeTeam` works, will use that
