### ISSUE TITLE
Some PlayerPawn props are always returning false.

### ISSUE THREAD

**Issue by B3none** [roflmuffin/CounterStrikeSharp#295]
`player.PlayerPawn.Value.InBombZone` is always false
`player.PlayerPawn.Value.IsDefusing` is always false

**Comment by roflmuffin** [comment]
Is this a CS# issue or is Valve just not using these?

**Comment by B3none** [comment]
> Is this a CS# issue or is Valve just not using these?

I think it’s a CS# issue because the bomb defusal logic uses both of these properties

**Comment by roflmuffin** [comment]
What about the `WhichBombZone` , `InBombZoneTrigger` props? There is also the `BombDefuser` Handle to a player pawn on the `CPlantedC4` which you could check

**Comment by B3none** [comment]
The BombDefuser handle does not work
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/24966460/4402e159-fa19-4ba5-be05-19b4fa604807)

`WhichBombZone` and `InBombZoneTrigger` work as expected

**Comment by roflmuffin** [comment]
For now I don't think there is anything we can do on our side; I don't see why this boolean would return anything differently unless Valve themselves are not using it; since its the same code path for all bools (and others work fine).
