### ISSUE TITLE
"Entry Point Not Found" on startup

### ISSUE THREAD

**Issue by DennisSkov** [roflmuffin/CounterStrikeSharp#302]
Whenever we start the server with CSSharp, we get an error stating the following:
> The procedure entry point ures_openDirect could not be located in the dynamic link library C:\Windows\SYSTEM32\icuin.dll

![billede](https://github.com/roflmuffin/CounterStrikeSharp/assets/5203348/9f5d0935-b01f-4be1-b24f-fe0eb12e2af8)

We've tested on various machines and it seems to be the same for all.
Tested on Windows Server 2019 with CSSharp v159 (although it has also happened with previous versions of the software).

**Comment by roflmuffin** [comment]
See #80, I think the icu lib required is only available in Windows Server 2022, but I cannot form
