### ISSUE TITLE
gameinfo.gi - do not edit this file directory (in csgo) - you probably want to edit csgo_core/gameinfo.gi

### ISSUE THREAD

**Issue by asheroto** [roflmuffin/CounterStrikeSharp#306]
In Getting Started, [Installing Metamod](https://docs.cssharp.dev/docs/guides/getting-started.html#installing-metamod), step 2, it says "gameinfo.gi" in "csgo". But at the top of that file it says...

```
// DO NOT EDIT THIS FILE DIRECTLY - YOU PROBABLY WANT TO EDIT CSGO_CORE/GAMEINFO.GI
```

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/49938263/b64eefd7-ed1c-4c40-885d-879eebd011d3)

I realize it may work fine in the `csgo/gameinfo.gi` file, but does it work in `csgo_core/gameinfo.gi`?

**Comment by crashzk** [comment]
@asheroto I have already tested editing this file in the `csgo_core` folder without success, it only works when editing from the `csgo` folder.

I took the test months ago, so just testing again to be sure.

**Comment by asheroto** [comment]
Gotcha! Just wanted to make sure! 😊 I'll go ahead and close this unless you find it needs to be opened. Thanks.
