### ISSUE TITLE
How do i use those APIs that did not have some comment just like "public CPointClientCommand(nint pointer)"?

### ISSUE THREAD

**Issue by ju1c3rSH** [roflmuffin/CounterStrikeSharp#307]
just like this:
https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CPointClientCommand.html

THANK YOU !!!!!  : )

**Comment by KillStr3aK** [comment]
try and find out is my mentality, or maybe dig around the binary/scripts/etc.. and see how it is being used by the game in the first place

**Comment by ju1c3rSH** [comment]
> try and find out is my mentality, or maybe dig around the binary/scripts/etc.. and see how it is being used by the game in the first place

thank you ，i'll try it as what you say
