### ISSUE TITLE
Menus are not opening after update to v160

### ISSUE THREAD

**Issue by AmbyCe** [roflmuffin/CounterStrikeSharp#308]
Hello,
after the update to v160, the behavior of the menus on my server changed.
It is still possible to open a menu, but when one menu calls to open another, the new menu will not appear. Is it on purpose, so a mistake on my part?

Thank you for your hard work

**Comment by roflmuffin** [comment]
The default behaviour for this has been reverted to reset which should resolve this. It is part of v161 release 👍
