### ISSUE TITLE
Failed to find signature for 'CEntityIOOutput_FireOutputInternal'

### ISSUE THREAD

**Issue by automixes** [roflmuffin/CounterStrikeSharp#309]
[1m[41m[16:50:21.689] CSSharp: Failed to find signature for 'CEntityIOOutput_FireOutputInternal'[m
/run.sh: line 44:  4905 Segmentation fault      $3

Metamod:Source version 2.0.0-dev+1281

**Comment by deadmau5v** [comment]
me too
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/88039301/c2587a4f-9bcc-4f39-a5d0-ce925743cd83)

**Comment by JustinSafrix** [comment]
Its entirely possible that with the big 8gb update today valve internally changed a variable name or outright removed it.

**Comment by denrio157** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/31591836/54aa3052-b08f-4991-9263-7cd18b05afca)

**Comment by JustinSafrix** [comment]
![Screenshot 2024-02-07 174146](https://github.com/roflmuffin/CounterStrikeSharp/assets/40339373/a1fdc330-dd00-41ba-b602-6e6a7b97eaaf)
Seems like this is an intended effect when looking at the source code. Not sure exactly what its used for but seems very important because it exits immediately if it can't find it

**Comment by Sniperlyf3** [comment]
Having this same issue.
Running on Ubuntu (All packages are up to date).
Latest version of Metamod
Latest version of CounterStrikeSharp
No other plugins
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/44154511/4102830e-0608-47a7-8c3e-62789c56aa47)

**Comment by VortDyn** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/54004093/f509029a-2e80-43fe-8228-772a6f95a69c)

**Comment by drakin001** [comment]
Yep, it's happening to everyone. Hopefully, it gets fixed soon.

**Comment by lashakaraulashvili** [comment]
copy and replace this in /game/csgo/addons/counterstrikesharp/gamedata/gamedata.json  for linux only
```
  "GameEventManager": {
    "offsets": {
      "windows": 93,
      "linux": 93
    }
  },
  "CEntityIOOutput_FireOutputInternal": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
  }
}
```

**Comment by automixes** [comment]
and remove ResourcePrecacher and BlockerPasses

> copy and replace this in /game/csgo/addons/counterstrikesharp/gamedata/gamedata.json for linux only
> 
> ```
>   "GameEventManager": {
>     "offsets": {
>       "windows": 93,
>       "linux": 93
>     }
>   },
>   "CEntityIOOutput_FireOutputInternal": {
>     "signatures": {
>       "library": "server",
>       "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
>       "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
>   }
> }
> ```

**Comment by seeuinhell95** [comment]
I modified gamedata.json but still the same:
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/11033614/a07b21d6-c487-4afc-9f1b-3d8bc89a5bae)

Even the same if i remove ResourcePrecacher

**Comment by Sniperlyf3** [comment]
Mine seems to be working fine after editing gamedata.json, will edit this if I get any issues

**Comment by seeuinhell95** [comment]
Update*

I removed AcceleratorLocal and now the server started.

**Comment by denrio157** [comment]
> copy and replace this in /game/csgo/addons/counterstrikesharp/gamedata/gamedata.json for linux only
> 
> ```
>   "GameEventManager": {
>     "offsets": {
>       "windows": 93,
>       "linux": 93
>     }
>   },
>   "CEntityIOOutput_FireOutputInternal": {
>     "signatures": {
>       "library": "server",
>       "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
>       "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
>   }
> }
> ```

I'm using on windows and still working rn, but sometimes making server disconnecting

**Comment by barlap** [comment]
Uh...Why does Valve ruin everything....

**Comment by Nianmou** [comment]
> 复制并替换 /game/csgo/addons/counterstrikesharp/gamedata/gamedata.json 仅适用于 Linux
> 
> ```
>   "GameEventManager": {
>     "offsets": {
>       "windows": 93,
>       "linux": 93
>     }
>   },
>   "CEntityIOOutput_FireOutputInternal": {
>     "signatures": {
>       "library": "server",
>       "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
>       "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
>   }
> }
> ```

  "CCSPlayerController_Respawn": {
    "offsets": {
        "windows": 244,
        "linux": 248
    }
  },
  "CCSPlayerPawn_Respawn": {
    "signatures": {
        "library": "server",
        "windows": "\\x40\\x53\\x48\\x83\\xEC\\x20\\x8B\\x91\\x38\\x0B\\x00\\x00\\x48\\x8B\\xD9",
        "linux": "\\x8B\\x8F\\x40\\x0E\\x00\\x00\\x83\\xF9\\xFF\\x0F\\x84\\xD9\\x01"
    }
  },

**Comment by ALegitCookie** [comment]
does anyone know a temporary fix for windows-based servers yet?

**Comment by roflmuffin** [comment]
The Linux fix for this will be fixed officially by Zonicals Gamedata update in #311 but we still don't have a windows sig for it

**Comment by CloudEMPG** [comment]
Replacing cs2/game/csgo/addons/counterstrikesharp/gamedata worked for me on linux server

`{
  "UTIL_ClientPrintAll": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x08\\x48\\x89\\x6C\\x24\\x10\\x48\\x89\\x74\\x24\\x18\\x57\\x48\\x81\\xEC\\x70\\x01\\x2A\\x2A\\x8B\\xE9",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xD7\\x41\\x56\\x49\\x89\\xF6\\x41\\x55\\x41\\x89\\xFD"
    }
  },
  "ClientPrint": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x85\\xC9\\x0F\\x84\\x2A\\x2A\\x2A\\x2A\\x48\\x8B\\xC4\\x48\\x89\\x58\\x18",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xCF\\x41\\x56\\x49\\x89\\xD6\\x41\\x55\\x41\\x89\\xF5\\x41\\x54\\x4C\\x8D\\xA5\\xA0\\xFE\\xFF\\xFF"
    }
  },
  "CCSPlayerController_SwitchTeam": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x56\\x57\\x48\\x81\\xEC\\x2A\\x2A\\x2A\\x2A\\x48\\x8B\\xF9\\x8B\\xF2\\x8B\\xCA",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x55\\x49\\x89\\xFD\\x89\\xF7"
    }
  },
  "CCSPlayerController_ChangeTeam": {
    "offsets": {
      "windows": 90,
      "linux": 89
    }
  },
  "CCSPlayerController_Respawn": {
    "offsets": {
        "windows": 242,
        "linux": 244
    }
  },
  "CCSPlayerPawn_Respawn": {
    "signatures": {
        "library": "server",
        "windows": "\\x40\\x53\\x48\\x83\\xEC\\x20\\x8B\\x91\\x38\\x0B\\x00\\x00\\x48\\x8B\\xD9",
        "linux": "\\x8B\\x8F\\x40\\x0E\\x00\\x00\\x83\\xF9\\xFF\\x0F\\x84\\xD9\\x01"
    }
  },
  "CCSPlayerPawnBase_PostThink": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x48\\x89\\x48\\x08\\x55\\x53\\x56\\x57\\x41\\x56\\x48\\x8D\\xA8\\xD8\\xFE\\xFF\\xFF",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x41\\x55\\x41\\x54\\x53\\x48\\x81\\xEC\\x2A\\x2A\\x2A\\x2A\\xE8\\x2A\\x2A\\x2A\\x2A\\x4C"
    }
  },
  "GiveNamedItem": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x18\\x48\\x89\\x74\\x24\\x20\\x55\\x57\\x41\\x54\\x41\\x56\\x41\\x57\\x48\\x8D\\x6C\\x24\\xD9",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x49\\x89\\xCE\\x41\\x55\\x49\\x89\\xF5\\x41\\x54\\x49\\x89\\xD4"
    }
  },
  "UTIL_Remove": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x85\\xC9\\x74\\x2A\\x48\\x8B\\xD1\\x48\\x8B\\x0D\\x2A\\x2A\\x2A\\x2A",
      "linux": "\\x48\\x89\\xFE\\x48\\x85\\xFF\\x74\\x2A\\x48\\x8D\\x05\\x2A\\x2A\\x2A\\x2A\\x48"
    }
  },
  "Host_Say": {
    "signatures": {
      "library": "server",
      "windows": "\\x44\\x89\\x4C\\x24\\x20\\x44\\x88\\x44\\x24\\x18",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x41\\x55\\x41\\x54\\x4D\\x89\\xC4"
    }
  },
  "CBaseModelEntity_SetModel": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x89\\x5C\\x24\\x10\\x48\\x89\\x7C\\x24\\x20\\x55\\x48\\x8B\\xEC\\x48\\x83\\xEC\\x50",
        "linux": "\\x55\\x48\\x89\\xF2\\x48\\x89\\xE5\\x41\\x54\\x49\\x89\\xFC\\x48\\x8D\\x2A\\x2A\\x48\\x83\\x2A\\x2A\\x2A\\x8D\\x05\\x2A\\x2A\\x2A\\x00\\x48\\x8B\\x30\\x48\\x8B\\x06\\xFF\\x2A\\x2A\\x48\\x8B\\x45\\x2A\\x48\\x8D\\x2A\\x2A\\x4C\\x89\\x2A\\x48\\x89\\x45\\x2A\\x2A\\x68\\xFC"
    }
  },
  "CCSPlayer_ItemServices_DropActivePlayerWeapon": {
    "offsets": {
        "windows": 18,
        "linux": 19
    }
  },
  "CCSPlayer_ItemServices_RemoveWeapons": {
      "offsets": {
          "windows": 21,
          "linux": 20
      }
  },
  "CGameSceneNode_GetSkeletonInstance": {
    "offsets": {
        "windows": 8,
        "linux": 8
    }
  },
  "CCSGameRules_TerminateRound": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x56",
        "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x49\\x89\\xFD\\x41\\x54\\x53\\x48\\x81\\xEC\\xE8"
      }
  },
  "UTIL_CreateEntityByName": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x83\\xEC\\x48\\xC6\\x44\\x24\\x30\\x00\\x4C\\x8B\\xC1",
        "linux": "\\x48\\x8D\\x05\\x2A\\x2A\\x2A\\x2A\\x55\\x48\\x89\\xFA"
      }
  },
  "CBaseEntity_DispatchSpawn": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x89\\x5C\\x24\\x10\\x57\\x48\\x83\\xEC\\x30\\x48\\x8B\\xDA\\x48\\x8B\\xF9\\x48\\x85\\xC9",
        "linux": "\\x48\\x85\\xFF\\x74\\x4B\\x55\\x48\\x89\\xE5\\x41\\x56"
      }
  },
  "CEntityInstance_AcceptInput": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x10\\x48\\x89\\x74\\x24\\x18\\x57\\x48\\x83\\xEC\\x40\\x49\\x8B\\xF0",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x48\\x8D\\x7D\\xC0"
    }
  },
  "LegacyGameEventListener": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\x15\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xD2\\x74\\x2A\\x85\\xC9\\x74",
      "linux": "\\x48\\x8B\\x05\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xC0\\x74\\x2A\\x83\\xFF\\x3F\\x76\\x2A\\x31\\xC0"
    }
  },
  "CBasePlayerPawn_CommitSuicide": {
    "offsets": {
      "windows": 357,
      "linux": 357
    }
  },
  "CBasePlayerPawn_RemovePlayerItem": {
    "signatures": {
      "library": "server",
      "linux": "\\x55\\x48\\x89\\x2A\\x41\\x2A\\x49\\x89\\x2A\\x41\\x2A\\x49\\x89\\x2A\\xE8\\x2A\\x2A\\x2A\\x2A\\x49\\x39",
      "windows": "\\x48\\x85\\xD2\\x0F\\x84\\x2A\\x2A\\x2A\\x2A\\x48\\x89\\x5C\\x24\\x08\\x57\\x48\\x83\\xEC\\x30\\x48\\x8B\\xDA"
    }
  },
  "CBaseEntity_Teleport": {
    "offsets": {
      "windows": 149,
      "linux": 148
    }
  },
  "CBaseEntity_TakeDamageOld": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x56\\x57\\x48\\x83\\xEC\\x58\\x48\\x8B\\x41\\x10",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xFC\\x53\\x48\\x83\\xEC\\x38\\x4C\\x8D\\x2D\\x2A\\x2A\\x2A\\x2A\\x49\\x8B\\x7D\\x00\\x48\\x85\\xFF\\x0F\\x84\\x2A\\x2A\\x2A\\x2A"
    }
  },
  "CBaseTrigger_StartTouch": {
    "signatures": {
      "library": "server",
      "windows": "\\x41\\x56\\x41\\x57\\x48\\x83\\xEC\\x58\\x48\\x8B\\x01",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x56\\x49\\x89\\xF6\\x41\\x55\\x49\\x89\\xFD\\x41\\x54\\x53\\xBB"
    }
  },
  "CBaseTrigger_EndTouch": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x53\\x57\\x41\\x55\\x48\\x83\\xEC\\x40",
      "linux": "\\x55\\xBA\\xFF\\xFF\\xFF\\xFF\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x49"
    }
  },
  "GameEntitySystem": {
    "offsets": {
      "windows": 88,
      "linux": 80
    }
  },
    "GameEventManager": {
    "offsets": {
      "windows": 93,
      "linux": 93
    }
  },
   "CEntityIOOutput_FireOutputInternal": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
    }
  }
}`

**Comment by CloudEMPG** [comment]
Replacing or editing "/cs2/game/csgo/addons/counterstrikesharp/gamedata" with the following worked for me.

{
  "UTIL_ClientPrintAll": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x08\\x48\\x89\\x6C\\x24\\x10\\x48\\x89\\x74\\x24\\x18\\x57\\x48\\x81\\xEC\\x70\\x01\\x2A\\x2A\\x8B\\xE9",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xD7\\x41\\x56\\x49\\x89\\xF6\\x41\\x55\\x41\\x89\\xFD"
    }
  },
  "ClientPrint": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x85\\xC9\\x0F\\x84\\x2A\\x2A\\x2A\\x2A\\x48\\x8B\\xC4\\x48\\x89\\x58\\x18",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xCF\\x41\\x56\\x49\\x89\\xD6\\x41\\x55\\x41\\x89\\xF5\\x41\\x54\\x4C\\x8D\\xA5\\xA0\\xFE\\xFF\\xFF"
    }
  },
  "CCSPlayerController_SwitchTeam": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x56\\x57\\x48\\x81\\xEC\\x2A\\x2A\\x2A\\x2A\\x48\\x8B\\xF9\\x8B\\xF2\\x8B\\xCA",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x55\\x49\\x89\\xFD\\x89\\xF7"
    }
  },
  "CCSPlayerController_ChangeTeam": {
    "offsets": {
      "windows": 90,
      "linux": 89
    }
  },
  "CCSPlayerController_Respawn": {
    "offsets": {
        "windows": 242,
        "linux": 244
    }
  },
  "CCSPlayerPawn_Respawn": {
    "signatures": {
        "library": "server",
        "windows": "\\x40\\x53\\x48\\x83\\xEC\\x20\\x8B\\x91\\x38\\x0B\\x00\\x00\\x48\\x8B\\xD9",
        "linux": "\\x8B\\x8F\\x40\\x0E\\x00\\x00\\x83\\xF9\\xFF\\x0F\\x84\\xD9\\x01"
    }
  },
  "CCSPlayerPawnBase_PostThink": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x48\\x89\\x48\\x08\\x55\\x53\\x56\\x57\\x41\\x56\\x48\\x8D\\xA8\\xD8\\xFE\\xFF\\xFF",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x41\\x55\\x41\\x54\\x53\\x48\\x81\\xEC\\x2A\\x2A\\x2A\\x2A\\xE8\\x2A\\x2A\\x2A\\x2A\\x4C"
    }
  },
  "GiveNamedItem": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x18\\x48\\x89\\x74\\x24\\x20\\x55\\x57\\x41\\x54\\x41\\x56\\x41\\x57\\x48\\x8D\\x6C\\x24\\xD9",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x49\\x89\\xCE\\x41\\x55\\x49\\x89\\xF5\\x41\\x54\\x49\\x89\\xD4"
    }
  },
  "UTIL_Remove": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x85\\xC9\\x74\\x2A\\x48\\x8B\\xD1\\x48\\x8B\\x0D\\x2A\\x2A\\x2A\\x2A",
      "linux": "\\x48\\x89\\xFE\\x48\\x85\\xFF\\x74\\x2A\\x48\\x8D\\x05\\x2A\\x2A\\x2A\\x2A\\x48"
    }
  },
  "Host_Say": {
    "signatures": {
      "library": "server",
      "windows": "\\x44\\x89\\x4C\\x24\\x20\\x44\\x88\\x44\\x24\\x18",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x41\\x55\\x41\\x54\\x4D\\x89\\xC4"
    }
  },
  "CBaseModelEntity_SetModel": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x89\\x5C\\x24\\x10\\x48\\x89\\x7C\\x24\\x20\\x55\\x48\\x8B\\xEC\\x48\\x83\\xEC\\x50",
        "linux": "\\x55\\x48\\x89\\xF2\\x48\\x89\\xE5\\x41\\x54\\x49\\x89\\xFC\\x48\\x8D\\x2A\\x2A\\x48\\x83\\x2A\\x2A\\x2A\\x8D\\x05\\x2A\\x2A\\x2A\\x00\\x48\\x8B\\x30\\x48\\x8B\\x06\\xFF\\x2A\\x2A\\x48\\x8B\\x45\\x2A\\x48\\x8D\\x2A\\x2A\\x4C\\x89\\x2A\\x48\\x89\\x45\\x2A\\x2A\\x68\\xFC"
    }
  },
  "CCSPlayer_ItemServices_DropActivePlayerWeapon": {
    "offsets": {
        "windows": 18,
        "linux": 19
    }
  },
  "CCSPlayer_ItemServices_RemoveWeapons": {
      "offsets": {
          "windows": 21,
          "linux": 20
      }
  },
  "CGameSceneNode_GetSkeletonInstance": {
    "offsets": {
        "windows": 8,
        "linux": 8
    }
  },
  "CCSGameRules_TerminateRound": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x56",
        "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x49\\x89\\xFD\\x41\\x54\\x53\\x48\\x81\\xEC\\xE8"
      }
  },
  "UTIL_CreateEntityByName": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x83\\xEC\\x48\\xC6\\x44\\x24\\x30\\x00\\x4C\\x8B\\xC1",
        "linux": "\\x48\\x8D\\x05\\x2A\\x2A\\x2A\\x2A\\x55\\x48\\x89\\xFA"
      }
  },
  "CBaseEntity_DispatchSpawn": {
    "signatures": {
        "library": "server",
        "windows": "\\x48\\x89\\x5C\\x24\\x10\\x57\\x48\\x83\\xEC\\x30\\x48\\x8B\\xDA\\x48\\x8B\\xF9\\x48\\x85\\xC9",
        "linux": "\\x48\\x85\\xFF\\x74\\x4B\\x55\\x48\\x89\\xE5\\x41\\x56"
      }
  },
  "CEntityInstance_AcceptInput": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x89\\x5C\\x24\\x10\\x48\\x89\\x74\\x24\\x18\\x57\\x48\\x83\\xEC\\x40\\x49\\x8B\\xF0",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x49\\x89\\xFF\\x41\\x56\\x48\\x8D\\x7D\\xC0"
    }
  },
  "LegacyGameEventListener": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\x15\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xD2\\x74\\x2A\\x85\\xC9\\x74",
      "linux": "\\x48\\x8B\\x05\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xC0\\x74\\x2A\\x83\\xFF\\x3F\\x76\\x2A\\x31\\xC0"
    }
  },
  "CBasePlayerPawn_CommitSuicide": {
    "offsets": {
      "windows": 357,
      "linux": 357
    }
  },
  "CBasePlayerPawn_RemovePlayerItem": {
    "signatures": {
      "library": "server",
      "linux": "\\x55\\x48\\x89\\x2A\\x41\\x2A\\x49\\x89\\x2A\\x41\\x2A\\x49\\x89\\x2A\\xE8\\x2A\\x2A\\x2A\\x2A\\x49\\x39",
      "windows": "\\x48\\x85\\xD2\\x0F\\x84\\x2A\\x2A\\x2A\\x2A\\x48\\x89\\x5C\\x24\\x08\\x57\\x48\\x83\\xEC\\x30\\x48\\x8B\\xDA"
    }
  },
  "CBaseEntity_Teleport": {
    "offsets": {
      "windows": 149,
      "linux": 148
    }
  },
  "CBaseEntity_TakeDamageOld": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x56\\x57\\x48\\x83\\xEC\\x58\\x48\\x8B\\x41\\x10",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xFC\\x53\\x48\\x83\\xEC\\x38\\x4C\\x8D\\x2D\\x2A\\x2A\\x2A\\x2A\\x49\\x8B\\x7D\\x00\\x48\\x85\\xFF\\x0F\\x84\\x2A\\x2A\\x2A\\x2A"
    }
  },
  "CBaseTrigger_StartTouch": {
    "signatures": {
      "library": "server",
      "windows": "\\x41\\x56\\x41\\x57\\x48\\x83\\xEC\\x58\\x48\\x8B\\x01",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x56\\x49\\x89\\xF6\\x41\\x55\\x49\\x89\\xFD\\x41\\x54\\x53\\xBB"
    }
  },
  "CBaseTrigger_EndTouch": {
    "signatures": {
      "library": "server",
      "windows": "\\x40\\x53\\x57\\x41\\x55\\x48\\x83\\xEC\\x40",
      "linux": "\\x55\\xBA\\xFF\\xFF\\xFF\\xFF\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x49"
    }
  },
  "GameEntitySystem": {
    "offsets": {
      "windows": 88,
      "linux": 80
    }
  },
    "GameEventManager": {
    "offsets": {
      "windows": 93,
      "linux": 93
    }
  },
   "CEntityIOOutput_FireOutputInternal": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x4C\\x89\\x48\\x20\\x55\\x57\\x41\\x54\\x41\\x56",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x41\\x54\\x49\\x89\\xD4\\x53\\x48\\x89\\xF3\\x48\\x83\\xEC\\x58"
    }
  }
}

**Comment by roflmuffin** [comment]
Should be fixed by v164 gamedata update
