### ISSUE TITLE
2/7/2024 Server wont start

### ISSUE THREAD

**Issue by y3request** [roflmuffin/CounterStrikeSharp#312]
I updated metamod so its working on my server.
I updated counterstrikesharp server crashes on start up loop.
**This is the error, 
[17:25:28.760] CSSharp: Failed to find signature for 'CEntityIOOutput_FireOutputInternal'**

I disabled all plugins and other metamods still wont start if cssharp is trying to load.

_my fix for now is running only metamod._

**Comment by ALegitCookie** [comment]
i am also having this issue. metamod and CSSharp completely up to date. just started happening after the new CS2 patch update. i believe the update has changed something which therefore has broken CSSharp for now. i think all we can do is wait for a fix.

**Comment by y3request** [comment]
> i am also having this issue. metamod and CSSharp completely up to date. just started happening after the new CS2 patch update. i believe the update has changed something which therefore has broken CSSharp for now. i think all we can do is wait for a fix.

unrelated to this thread, but i am curious of a second issue, also unrelated to metamod or cssharp. 
If you have bots on your server, when you connect, then leave. Does it still show you ask taking a slot? People are joining my server, when they leave slot stays. I think valve broke multiple things LOL.

**Comment by ALegitCookie** [comment]
> > i am also having this issue. metamod and CSSharp completely up to date. just started happening after the new CS2 patch update. i believe the update has changed something which therefore has broken CSSharp for now. i think all we can do is wait for a fix.
> 
> unrelated to this thread, but i am curious of a second issue, also unrelated to metamod or cssharp. If you have bots on your server, when you connect, then leave. Does it still show you as taking a slot? (For example if its 6/10 you join, bot leaves. Then you leave, bot comes back and shows 7/10.) People are joining my server, when they leave slot stays. I think valve broke multiple things LOL.

unfortunately i have not been in a situation where this would happen. i am actually in the process of building my cs2 server right now so I haven't had anyone join except myself. and i've had bots off the entire time. i hope you get it figured out, though. that's weird.

**Comment by y3request** [comment]
> i'm still just pissed that cs2 replaced GO in the first place lol. i used to have like 5 servers i spent hours configuring and of course they're now useless. so im still starting again from scratch lol.

Yeah its a bit rough atm. Every time you get it set up perfectly, something happens. Mostly Valve poking around. The community coders are fast.

**Comment by deadmau5v** [comment]
https://github.com/roflmuffin/CounterStrikeSharp/issues/309#issuecomment-1932484076

**Comment by KillStr3aK** [comment]
#314
