### ISSUE TITLE
ChangeTeam Bug

### ISSUE THREAD

**Issue by shakidevcom** [roflmuffin/CounterStrikeSharp#316]
CsTeam team = GetPlayerTeam(player);

player.ChangeTeam(team);

when user connected, will set team, but he cant move and play, just like spectator in one area

**Comment by xLeviNx** [comment]
https://github.com/roflmuffin/CounterStrikeSharp/pull/315#issuecomment-1935172398

**Comment by shakidevcom** [comment]
same bug after update cs2 tomorrow

**Comment by roflmuffin** [comment]
Please confirm if this issue still occurs after most recent gamedata updates.
