### ISSUE TITLE
Running dedicated server with CS# and CS2 client at the same time?

### ISSUE THREAD

**Issue by stevefan1999-personal** [roflmuffin/CounterStrikeSharp#335]
It is currently not possible to run CS# and the CS2 client at the same time, making development difficult on local machine (CS2 client would crash with CS# plugin loaded with server side related stuff missing), so now I have to designate a VM to run the dedicated server (which at the moment is running inside a WSL2 instance) and then use VSCode Remote to indirectly have a reasonable development workflow (technically speaking I can also use a real remote machine for that, but debugging would be painful). 

I prefer to have all the development workflow under Windows though, as WSL2 takes a performance toll (especially memory) quite much.

**Comment by roflmuffin** [comment]
This is not a CS# issue, it was the same with CSGO. Iirc you must run them in a specific order to prevent the already running error.

**Comment by stevefan1999-personal** [comment]
> This is not a CS# issue, it was the same with CSGO. Iirc you must run them in a specific order to prevent the already running error.

Interesting. So I took that as a Wontfix. Closing for now, but do keep in mind about this restriction in readme is recommended
