### ISSUE TITLE
Artifact crashes the whole app

### ISSUE THREAD

**Issue by Veeksi** [roflmuffin/CounterStrikeSharp#34]
Hey,

I downloaded this artifact: https://github.com/roflmuffin/CounterStrikeSharp/actions/runs/6782595525 and I get these texts so it seems like it succesfully initializes:
```
[12:38:16.708] CSSharp: Initializing
[12:38:16.708] CSSharp: Globals loaded.
[12:38:16.721] CSSharp: .NET Runtime Initialised.
Loading GameData
Loaded game data with 8 methods.
Loading C# plugins...
All managed modules were loaded. 0 plugins loaded.
[12:38:16.866] CSSharp: CounterStrikeSharp.API Loaded Successfully.
[12:38:16.866] CSSharp: Hooks added.
```

However meta list command returns this where [01] and [04] are added when adding that counterstrikesharp runtime:
```
Listing 4 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] Fake RCON (1.2.1) by Kriax
  [03] Base Admin (1.2) by Pisex
  [04] <FAILED>
```

Also when joining to server, the whole server crashes. All these issues disappear when removing `addons/counterstrikesharp/*` and `metamod/counterstrikesharp.vdf` files. 

Any ideas what should I test?

**Comment by roflmuffin** [comment]
You will probably find limited support with running CSSharp with any other metamod plugins at the moment

**Comment by Veeksi** [comment]
> You will probably find limited support with running CSSharp with any other metamod plugins at the moment

Ahh so I cannot use metamod and CSSharp plugins together?

**Comment by roflmuffin** [comment]
Its hard to say, but at the moment a lot of metamod plugins use dynamic hooks which conflict with each other so you will received mixed results or unexpected errors.

**Comment by Veeksi** [comment]
> Its hard to say, but at the moment a lot of metamod plugins use dynamic hooks which conflict with each other so you will received mixed results or unexpected errors.

Okay nice to hear. I was thinking to use this plugin: https://github.com/ManifestManah/MapConfigurator that uses CSSharp but I think I have to wait until those conflicts are resolved.

**Comment by roflmuffin** [comment]
Right now we are only planning compat with CS2fixes, tracked in #94
