### ISSUE TITLE
Server.PrecacheModel does not take effect (?)

### ISSUE THREAD

**Issue by ELDment** [roflmuffin/CounterStrikeSharp#341]
I have tested this API on Linux and Windows platforms, but it cannot precache my model as expected (the proof is **when I use _"CBaseModelEntity.SetModel()"_**, the system prompts **the model file cannot be found**.)
Ps. 
- I used **_Server.PrecacheModel()_** on OnMapStart.
- the **_"(?)"_** in the title indicates that I am not 100% certain about it **(it may be due to my improper use)**
- **If my usage is incorrect, please guide me!** 🎈

**Comment by roflmuffin** [comment]
Precaching has changed significantly since CSGO, which is what these precache methods are based on, so it's possible they don't work.

More work needs to be done to support this natively, Killstreak has done a plugin for custom resources: https://github.com/KillStr3aK/ResourcePrecacher

**Comment by samyycX** [comment]
> Precaching has changed significantly since CSGO, which is what these precache methods are based on, so it's possible they don't work.
> 
> More work needs to be done to support this natively, Killstreak has done a plugin for custom resources: https://github.com/KillStr3aK/ResourcePrecacher

Will this plugin be embedded into counterstrikesharp in the future?

**Comment by roflmuffin** [comment]
> > Precaching has changed significantly since CSGO, which is what these precache methods are based on, so it's possible they don't work.
> > More work needs to be done to support this natively, Killstreak has done a plugin for custom resources: https://github.com/KillStr3aK/ResourcePrecacher
> 
> Will this plugin be embedded into counterstrikesharp in the future?

The plugin won't be, but a method to do what this plugin does within your own plugin would be.

**Comment by KillStr3aK** [comment]
We could implement a custom gamesystem to ensure resource precaching

**Comment by KillStr3aK** [comment]
#358

**Comment by B3none** [comment]
It looks like this was implemented, if I'm wrong, or if you think this is still an issue please re-open the issue.
