### ISSUE TITLE
`css_lang` command has no effect

### ISSUE THREAD

**Issue by Delfram99** [roflmuffin/CounterStrikeSharp#347]
I'm using the latest build v175 and experiencing an issue with the `css_lang` command. When I use it, no changes are applied and translations do not take effect. Even rejoining the server does not resolve the issue. Furthermore, after a server restart, the setting resets to its default value for the player.

**Comment by roflmuffin** [comment]
Do you know if this is a regression? We have never persisted the server language across server restarts, as this is just kept in memory after a user types `!lang en`, but a custom plugin does have the ability to persist this if they wanted to. Which plugin are you using to confirm the translations are not working?
