### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Draakoor** [roflmuffin/CounterStrikeSharp#356]
Since the lastest cs2 update my server keep crashing.

Consolelog:
`[CS2Fixes] Starting plugin.
All hooks started!
[CS2Fixes] Loading addons/cs2fixes/gamedata/cs2fixes.games.txt for game: csgo
[CS2Fixes] Initialized module engine2 base: 0x0x7fc4a657e000 | size: 4833280
[CS2Fixes] Initialized module tier0 base: 0x0x7fc4a7ee5000 | size: 3112960
[CS2Fixes] Initialized module server base: 0x0x7fc4798ab000 | size: 14417920
[CS2Fixes] Initialized module schemasystem base: 0x0x7fc4a0a36000 | size: 335872
[CS2Fixes] Initialized module vscript base: 0x0x7fc481bbf000 | size: 741376
[CS2Fixes] Initialized module networksystem base: 0x0x7fc481838000 | size: 2576384
[CS2Fixes] Found NetworkStateChanged at 0x0x7fc47a546fe0
[CS2Fixes] Found StateChanged at 0x0x7fc47996da30
[CS2Fixes] Found UTIL_ClientPrintAll at 0x0x7fc47a298c40
[CS2Fixes] Found ClientPrint at 0x0x7fc47a062220
[CS2Fixes] Found SetGroundEntity at 0x0x7fc47a1c01b0
[CS2Fixes] Found CCSPlayerController_SwitchTeam at 0x0x7fc479f2a570
[CS2Fixes] Found CBasePlayerController_SetPawn at 0x0x7fc479f74c10
[CS2Fixes] !!!!!!!!!! Signature for CBaseModelEntity_SetModel occurs multiple times! Using first match but this might end up crashing!
[CS2Fixes] Found CBaseModelEntity_SetModel at 0x0x7fc479f62c70
[CS2Fixes] Found UTIL_Remove at 0x0x7fc479fdaa20
[CS2Fixes] Found CEntitySystem_AddEntityIOEvent at 0x0x7fc47a53f670
[CS2Fixes] Found CEntityInstance_AcceptInput at 0x0x7fc47a527730
[CS2Fixes] Found CGameEntitySystem_FindEntityByClassName at 0x0x7fc479fd9100
[CS2Fixes] Found CGameEntitySystem_FindEntityByName at 0x0x7fc479fd9170
[CS2Fixes] Found CGameRules_TerminateRound at 0x0x7fc479e19090
[CS2Fixes] Found CreateEntityByName at 0x0x7fc479fda720
[CS2Fixes] Found DispatchSpawn at 0x0x7fc47a05d3e0
[CS2Fixes] Found CEntityIdentity_SetEntityName at 0x0x7fc47a523720
[CS2Fixes] Found CBaseEntity_EmitSoundParams at 0x0x7fc47a0a6740
[CS2Fixes] Found CBaseEntity_SetParent at 0x0x7fc479acecc0
[CS2Fixes] Failed to find address for ServerMovementUnlock
[CS2Fixes] Patched VScriptEnable at 0x7fc481bc4a9d
[CS2Fixes] Patched FixWaterFloorJump at 0x7fc479f1d9c8
[CS2Fixes] Patched CategorizeUnderwater at 0x7fc479f1ad44
[CS2Fixes] Patched WaterLevelGravity at 0x7fc479f04efe
[CS2Fixes] !!!!!!!!!! Signature for BotNavIgnore occurs multiple times! Using first match but this might end up crashing!
[CS2Fixes] Patched BotNavIgnore at 0x7fc479a172b5
[CS2Fixes] !!!!!!!!!! Signature for BotNavIgnore occurs multiple times! Using first match but this might end up crashing!
[CS2Fixes] Patched BotNavIgnore at 0x7fc479a173b5
[CS2Fixes] Patched BotNavIgnore at 0x7fc479a177ee
[CS2Fixes] Detoured Msg at 0x0x7fc4a7f24b10
[CS2Fixes] Detoured ConDMsg at 0x0x7fc4a7f257b0
[CS2Fixes] Detoured DevMsg at 0x0x7fc4a7f25140
[CS2Fixes] Detoured Warning at 0x0x7fc4a7f24c20
[CS2Fixes] Detoured DevWarning at 0x0x7fc4a7f25260
[CS2Fixes] Detoured LoggingSystem_Log at 0x0x7fc4a7fa34d0
[CS2Fixes] Detoured LoggingSystem_LogDirect at 0x0x7fc4a7fa3cb0
[CS2Fixes] Detoured LoggingSystem_LogAssert at 0x0x7fc4a7fa4060
[CS2Fixes] Detoured UTIL_SayTextFilter at 0x0x7fc47a298d90
[CS2Fixes] Detoured UTIL_SayText2Filter at 0x0x7fc47a298fb0
[CS2Fixes] Detoured IsHearingClient at 0x0x7fc4a6777b00
[CS2Fixes] Detoured CSoundEmitterSystem_EmitSound at 0x0x7fc47a2397e0
[CS2Fixes] Detoured TriggerPush_Touch at 0x0x7fc47a2918e0
[CS2Fixes] Detoured CGameRules_Constructor at 0x0x7fc47a147520
[CS2Fixes] Detoured CBaseEntity_TakeDamageOld at 0x0x7fc479ad1670
[CS2Fixes] Detoured CCSPlayer_WeaponServices_CanUse at 0x0x7fc479f31e80
[CS2Fixes] Detoured CEntityIdentity_AcceptInput at 0x0x7fc47a5238a0
[CS2Fixes] Detoured CNavMesh_GetNearestNavArea at 0x0x7fc47a585590
[CS2Fixes] Detoured FixLagCompEntityRelationship at 0x0x7fc479b82250
[CS2Fixes] Detoured SendNetMessage at 0x0x7fc481909170
[CS2Fixes] Detoured HostStateRequest at 0x0x7fc4a6625650
Event System loaded 93 events from file: vpk:/home/container/game/core/pak01.vpk:resource/core.gameevents.
Event System loaded 51 events from file: vpk:/home/container/game/csgo/pak01.vpk:resource/game.gameevents.
Event System loaded 152 events from file: vpk:/home/container/game/csgo/pak01.vpk:./resource/mod.gameevents.
Wrote minidump to: /home/container/game/csgo/addons/accelerator_local/dumps/afa2f013-5b07-467c-3a9b7e83-7b709347.dmp
2024-02-29 08:29:37: minidump.cc:./game/cs2.sh: line 118:    43 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

**Comment by KillStr3aK** [comment]
> Signature for [...] occurs multiple times! Using first match but this might end up crashing!

also it seems to be related to cs2fixes?
