### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by asdfxD** [roflmuffin/CounterStrikeSharp#36]
compiled without error but server crashes.

[19:43:13.904] CSSharp: Initializing
[19:43:13.904] CSSharp: Globals loaded.
cs2: /root/counterstrikesharp/src/scripting/dotnet_host.cpp:59: void* {anonymous}::load_library(const char_t*): Assertion `h != nullptr' failed.

**Comment by roflmuffin** [comment]
You need to include the dotnet runtime, this error indicates it cannot load the .net runtime from `addons/counterstrikesharp/dotnet/host/fxr/7.0.11/libhostfxr.so`

**Comment by KillStr3aK** [comment]
I think this can be closed?
