### ISSUE TITLE
Add RunInNTicks or RunOnTick

### ISSUE THREAD

**Issue by busheezy** [roflmuffin/CounterStrikeSharp#367]
It would be great to be able to do things like "run in 3 ticks."

```csharp
RunInNTicks(3, () => Logger.LogInformation("wooo, 3 ticks!"));
```

and/or

```csharp
var futureTick = Server.TickedTime + 3;
RunOnTick(futureTick, () => Logger.LogInformation("wooo, 3 ticks!"));
```

This has been discussed briefly here: https://github.com/roflmuffin/CounterStrikeSharp/issues/354#issuecomment-1980129038

**Comment by dran1x** [comment]
Killstreak made something for this a while ago, don't know if it still works or not.

https://discord.com/channels/1160907911501991946/1160925208203493468/1171270690016600114

**Comment by busheezy** [comment]
Yep, it's mentioned in the comment linked above.

**Comment by dran1x** [comment]
I was going to bring an issue up sooner or later about integrating it into CS#, it's nice.
