### ISSUE TITLE
Add ability to rename bots

### ISSUE THREAD

**Issue by Jarzka** [roflmuffin/CounterStrikeSharp#372]
It would be nice to rename bots on the server. Is there any way to do it? I tried the following code, but it did not work (name was not changed):

```csharp
  [GameEventHandler]
  public HookResult OnPlayerSpawned(EventPlayerSpawned @event, GameEventInfo info)
  {
    if (@event.Userid.IsValid)
    {
      Console.WriteLine("Player has spawned: " + @event.Userid.PlayerName);
      @event.Userid.PlayerName = "Duke Nukem";
    }

    return HookResult.Continue;
  }
```

**Comment by roflmuffin** [comment]
You will need to use `CCSBot.Name` rather than player name. You would probably be best to find help on this on the Discord server

**Comment by Jarzka** [comment]
How do I access `CCSBot.Name`? `@event.UserId` returns `CCSPlayerController` which has no information about `CCSBot` 🤔

**Comment by roflmuffin** [comment]
You'll need to get access to the Pawn and then you can use the `.As<CCSBot>()` helper to cast it to a bot.

**Comment by Jarzka** [comment]
Thanks for help.

I tried renaming the bot by doing:

```csharp
CCSBot bot = @event.Userid.Pawn.Value.As<CCSBot>();
bot.Name = "Duke Nukem";
Console.WriteLine("Name changed to: " + bot.Name);
`````

According to the console message, the bot name should ne changed, but when running `status` command on my server it seems that nothing has actually changed. Also, when I join my server and add a bot player, the original names are still in place. 😞

**Comment by roflmuffin** [comment]
I think you may also need to call the `SetStateChanged `utility, which basically tells the server that this value has changed and needs to be propagated to clients.

`Utilities.SetStateChanged(bot, "CCSBot", "m_name");`

**Comment by Jarzka** [comment]
I'm not exactly sure how to pass `bot` to `SetStateChanged` since that function required a class of `CBaseEntity` and `CCSBot` is not inherited from it.

I tried using `As` casting and I think it worked, but I got an error that bot `m_name` is not networked. I also tried `m_Name` and got the same result:

```
17:59:10 [WARN] (cssharp:Core) Field CCSBot:m_name is not networked, but SetStateChanged was called on it.
17:59:10 [WARN] (cssharp:Core) Field CCSBot:m_Name is not networked, but SetStateChanged was called on it.
```

**Comment by ianlucas** [comment]
I think it's worth trying to edit that in a early game event, like OnPlayerConnect/OnPlayerConnectFull, since this field is not networked.

**Comment by Jarzka** [comment]
Good point! I tried using the renaming in both `OnPlayerConnect` and `OnPlayerConnectFull` events but unfortunately neither of these worked.

**Comment by B3none** [comment]
Give me a ping on discord and we'll find a working solution for you 👍

**Comment by Jarzka** [comment]
Could you give me the solution here or at least suggest what to do? I do not use Discord and even if I did, I think it would be best to solve the problem here so that others can also see it.

**Comment by B3none** [comment]
> Could you give me the solution here or perhaps suggest what to do? I do not use Discord and even if I did, I think it would be best to solve the problem here so that others can also see it.

Was this possible in CS:GO? https://forums.alliedmods.net/showpost.php?p=2035935&postcount=3

**Comment by roflmuffin** [comment]
> Could you give me the solution here or perhaps suggest what to do? I do not use Discord and even if I did, I think it would be best to solve the problem here so that others can also see it.

The main reason I try to keep this kind of discussion off of Github is because I would prefer GH issues to be issues relevant to the framework that can be fixed/added etc. This kind of issue is more a matter of reverse engineering effort and trial & error by individuals to see how Valves code actually works/investigate how these schema values actually propagate values across.

**Comment by Jarzka** [comment]
> Was this possible in CS:GO? 

CS:GO has built-in support for renaming bots on the server without plugins by configuring a file named `Botprodile.db`. This file does not exists in CS2 (or maybe it's a part of the .vpk files, where it cannot be easily modified without getting file validation errors). 

> This kind of issue is more a matter of reverse engineering effort and trial & error by individuals to see how Valves code actually works

Okay, sorry, I didn't know this might cause reverse engineering. I though there is already a way to do it, I just don't know how. 😆

**Comment by y3request** [comment]
>   CS:GO has built-in support for renaming bots on the server without plugins by configuring a file named `Botprofile.db`. This file does not exist in CS2, which is why I'm looking for an alternative solution.
> 
I was watching this thread hoping you guys found a way. 
I miss botprofile.db, the file still exists inside the games .pak files but you cannot change it of course (i tried). 
When this file existed you could change bot names, the pitch of their voice and more. 
You also used to be able to edit the ai profiles too, but now you also cannot do this either. I wish valve put some of the files back outside the pak files. 
Maybe one day the server plugins can call their own .db .ai files?

**Comment by Jarzka** [comment]
It seems that there IS a way to rename bots using the good old Botprofile.db in CS2. Look here: https://www.reddit.com/r/GlobalOffensive/comments/16u8175/comment/kxolry1

**Comment by y3request** [comment]
> It seems that there IS still a way to rename bots using the good old Botprofile.db in CS2. Look here: https://www.reddit.com/r/GlobalOffensive/comments/16u8175/comment/kxolry1

it works, thanks man.
