### ISSUE TITLE
Collision Group consts define is wrong.

### ISSUE THREAD

**Issue by chenbuyi2019** [roflmuffin/CounterStrikeSharp#375]
[css define](https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Modules/Entities/Constants/CollisionGroup.cs) is different from [alliedmodders/hl2sdk cs2](https://github.com/alliedmodders/hl2sdk/blob/cs2/public/const.h) `enum Collision_Group_t`.  
i think the hl2sdk cs2 one would be correct.   
I was thinking why I set a prop to WEAPON and it still collides to player.   
Turns out, it was the wrong number. 
COLLISION_GROUP_WEAPON shall be 14 not 11.  
COLLISION_GROUP_PUSHAWAY shall be 20 not 17.

**Comment by chenbuyi2019** [comment]
and some test result of mine : https://buyi.dev/2024/cs2-collisiongroup/

**Comment by roflmuffin** [comment]
Thanks for the report, would you be able to test using the generated API artifact from this PRs latest build and re-run your tests. I've updated the enum to the same as hl2sdk

https://github.com/roflmuffin/CounterStrikeSharp/pull/376

**Comment by chenbuyi2019** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/26303007/5cfbba05-b078-44b1-a2d9-99055ae6d910)
it is now ok and good.
