### ISSUE TITLE
Chat detour

### ISSUE THREAD

**Issue by arildboifot** [roflmuffin/CounterStrikeSharp#38]
First, thanks for a fantastic project! 💯 

I noticed that the chat detour auto dispatches anything that stars with '/' and '!'. This creates a few problems for us since we have some other infrastructure that needs to know about chats that starts with '!'. 

Also I found that it's not possible to implement a '!pause' command since pause is already a command (leads to seg fault). 

I see a couple of solutions here that would fit nicely for us at least. 

1. Always do m_pHostSay
2. Configuration to turn off chat commands

What do you think?

**Comment by roflmuffin** [comment]
We have plans to make the chat triggers configurable. You can also declare your command as `css_pause` and this will get aliased to `!pause` in chat.

**Comment by arildboifot** [comment]
Got it! The css_ prefix trick will do for now. Thanks!

**Comment by roflmuffin** [comment]
Silent and public triggers are live as of v52, but not yet configurable.
