### ISSUE TITLE
map change crash

### ISSUE THREAD

**Issue by brkvlr** [roflmuffin/CounterStrikeSharp#383]
[39;49m[37m20:24:03[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 123[39;49m
[39;49m[37m   at Advertisement.Ads.<Load>b__10_1(EventPlayerDisconnect event, GameEventInfo _)[39;49m
[39;49m[37m   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120[39;49m

**Comment by B3none** [comment]
> �[39;49m�[37m ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')�[39;49m
> �[39;49m�[37m at CounterStrikeSharp.API.Core.CBasePlayerController.get_SteamID() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs:line 123�[39;49m

Make sure you're checking to ensure that player is valid / not null before you try calling `getSteamID()`

**Comment by B3none** [comment]
Closing as this is a plugin issue, and not one with CounterStrikeSharp.
