### ISSUE TITLE
Questions about using MaxMind's GeoIP2 GeoLite2 Country, City, and ASN databases

### ISSUE THREAD

**Issue by crashzk** [roflmuffin/CounterStrikeSharp#392]
Some plugins use these databases: https://github.com/P3TERX/GeoLite.mmdb

However, all plugins you use need to place these databases in the plugin folder in question.

I would like to know if it would be interesting to include this database in CSSharp directly? A folder where these databases would be located and the plugin you need just searches there. This way we can avoid multiple database versions, one for each plugin.

It could be located in the `addons/counterstrikesharp/configs/geoip` folder

Or there would be a reason for how it works now, so it wouldn't be possible to change it.

**Comment by roflmuffin** [comment]
Plugin authors can place and use these from the shared folder (at the same level as plugins), but there isn't any plans to ship this with the framework

**Comment by crashzk** [comment]
I understand, I think it would be quite impractical for me to have to update folder by folder with these GEOIP in all the plugins I use whenever there is an update to these databases, so leaving something "centralized" would be interesting.

Anyway, thanks for the explanation.
