### ISSUE TITLE
CS2 servers

### ISSUE THREAD

**Issue by HexMr** [roflmuffin/CounterStrikeSharp#393]
Hello, I'm asking out of curiosity whether using your tool it is possible to make the community server appear multiple times in the Internet tab, as some people do, I know it's possible that they edited the "tiny-csgo-server" repository but I'm just curious. I wonder if something like this can also be done with your tool, e.g. by uploading a plugin to the server. If it is feasible, would you say what to use for it?

**Comment by KillStr3aK** [comment]
things like this are no discuss, also not an issue

**Comment by HexMr** [comment]
@KillStr3aK I'm just curious if your tool allows you to do something like this, I haven't had CS servers for a long time but I've been involved with it since I was a child and I'm just curious, so I'm asking out of pure curiosity, I'm curious if your tool is able to to do something so complicated. I would be grateful if you answered me, if not here, then in an email or other messenger. As an IT person, I am curious about the possibilities of your program.

**Comment by HexMr** [comment]
@roflmuffin

**Comment by crashzk** [comment]
I believe you can try discord for a discussion like this: https://discord.gg/eAZU3guKWU

But let me warn you, I don't know if a discussion like that will be welcome there. From what I understand, you are trying to find out if there is any way to make a fake server, a fake server with fake players, right? I believe so, now how and where to start this is up to you.

But I wonder why curiosity like this? Anyway, that's it.

**Comment by roflmuffin** [comment]
This is not supported in cs# and probably won't be facilitated by the community

**Comment by HexMr** [comment]
> I believe you can try discord for a discussion like this: https://discord.gg/eAZU3guKWU
> 
> But let me warn you, I don't know if a discussion like that will be welcome there. From what I understand, you are trying to find out if there is any way to make a fake server, a fake server with fake players, right? I believe so, now how and where to start this is up to you.
> 
> But I wonder why curiosity like this? Anyway, that's it.

I'd love to talk to you about it, add me on discord, my discord name is hievnn
