### ISSUE TITLE
CenterHtmlMenu Open method in a weird state.

### ISSUE THREAD

**Issue by frederikstonge** [roflmuffin/CounterStrikeSharp#395]
Not really an issue, but something is missing here in the new CenterHtmlMenu change to support Open method.
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/5427239/01d4c05a-771b-4775-b0a9-c21fcf8458e3)

IMO, we should either remove the constructor without the BasePlugin :
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/5427239/76c5d123-621f-42b5-9511-cdab16d778ac)

OR, throw an exception if the BasePlugin is null to inform the user that he has used the wrong constructor :

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/5427239/02537e61-9328-45eb-9312-85be4ae91104)

**Comment by roflmuffin** [comment]
I agree, I almost requested this as a CR in the PR but decided against it but I think throwing the exception makes sense
