### ISSUE TITLE
Player's money not updating on HUD

### ISSUE THREAD

**Issue by WeirdPhrog** [roflmuffin/CounterStrikeSharp#397]
Hi, when I give a player some money during freeze time, the player doesn't see any changes on HUD until freeze time ends. Please help.

I tried Utilities.SetStateChanged(playerPawn!, "CCSPlayerController_InGameMoneyServices", "m_iAccount"); but nothing changed. 

v 204

**Comment by roflmuffin** [comment]
Do this instead, it needs to be done on the controller not the pawn, and the item to mark as state changed should be the whole reference to money services.

`SetStateChanged(controller, "CCSPlayerController", "m_pInGameMoneyServices");`
