### ISSUE TITLE
Crashing problem with bots

### ISSUE THREAD

**Issue by brkvlr** [roflmuffin/CounterStrikeSharp#403]
https://crash.limetech.org/gpbqsgcewih5
https://crash.limetech.org/du54hfootpfp

can you help me?

**Comment by xLeviNx** [comment]
What makes you think there are any issues with cs# and bots?

**Comment by brkvlr** [comment]
My server with bots only crashes like this, what else could be the problem?

**Comment by xLeviNx** [comment]
Not related to cs# itself. You have some plugin causing this.

**Comment by iWanheda** [comment]
> I think it's from this plugin, but I can't access the detailed error log. https://github.com/NockyCZ/CS2-Deathmatch
> 
> [console (26).log](https://github.com/roflmuffin/CounterStrikeSharp/files/14911194/console.26.log)

Your console log contains your (or whoever joined the server) IP address, should be more careful.

**Comment by brkvlr** [comment]
bot_join_after_player "1" // 
When set to 1 I experience a lot of crashes, when set to 0 there is no problem
