### ISSUE TITLE
Add admin functionality

### ISSUE THREAD

**Issue by Porcellacion** [roflmuffin/CounterStrikeSharp#41]
Since CSSharp is taking off rapidly, and large amounts of plugins are being created, I'd like to suggest a long-term solution here.
A lot of plugins have unique **admins.cfg** files. This will be confusing for the average user when adding multiple plugins.

I'd advise CSSharp to add a base **admins.cfg** file that works similar to how it did in SourceMod: [https://wiki.alliedmods.net/Adding_Admins_(SourceMod)](url)

This way, the average user (and plugin creator) will save a lot of time, both in terms of developing an admin system, but also to manage the plugins.

**Comment by KillStr3aK** [comment]
Sourcemod comes with alot of builtin plugins by default, and the admin system is one of them. we might have builtin plugins by default in the future but I'm not sure if the admin system should be supported by the core or not. I mean its a great thing for sure, and also has benefits (like centralized admin tools) but also comes with many limitations, just like in sourcemod. We would have to come up with a better idea than using (random number) 15 flags at all for everything, more like named permissions for e.g.

I'm curious what will be the decision on this and how it progresses further

**Comment by Porcellacion** [comment]
Good points. But yea, I'm sure that we'll see much bigger issues with multiple different admin configurations.
Just an example of already existing mods with different admin files:

- MatchZy
- MapChooser
- Mini Admin
- PugSharp
- ServerManagement

In a few months, we'll be grateful that we added one core file for this.

**Comment by zonical** [comment]
I like the idea of a core file approach, but I think we should let individual plugins handle implementing their own systems for handling mutes, bans, etc.

**Comment by crashzk** [comment]
Can we still expect this since the mentioned PR has been closed?

**Comment by Max66888** [comment]
Will there be a situation where Minecraft subdivides and divides permission groups for each permission
For example, each function or instruction can be given separately
Then, based on this, establish a flag a such as sourcemod and include a series of permissions
But it seems that it is necessary for the plugin to comply with the specifications. Can each instruction have its own permissions set?
