### ISSUE TITLE
playerPawn vs playerPawn.Value, etc

### ISSUE THREAD

**Issue by WeirdPhrog** [roflmuffin/CounterStrikeSharp#412]
What's the difference between playerPawn and playerPawn.Value? weapon and weapon.Value? etc. What should I work with and when? What should I check for null and IsValid? Where can I read about this?

**Comment by Yarukon** [comment]
playerPawn is the handle of the pawn, playerPawn.Value is the actual entity

**Comment by WeirdPhrog** [comment]
Should I also check handler of the entity for valid?

**Comment by roflmuffin** [comment]
When you access `.Value` or `.Get()` on a handle, it will return null if its invalid, so you only need to check for null after accessing the value.
