### ISSUE TITLE
GameEvent listener improvement

### ISSUE THREAD

**Issue by Kroytz** [roflmuffin/CounterStrikeSharp#413]
I found ```item_equip``` only fire once when I receive an item but not like CSGO does(fire at everytime weapon switch). Seems like ```CreateEvent``` function fails sometimes. So we can add a hook for ```CreateEvent``` and make the bForce always true. IDK why it works at least it works for me.

**Comment by Kroytz** [comment]
Sorry I found HookEvent logic has done the same logic (FindListener then AddListener)

**Comment by Kroytz** [comment]
Test again with hook CreateEvent and change param bForce = true, then ```item_equip``` event works as expected.

**Comment by roflmuffin** [comment]
I'm not sure we should really be changing this bool, because the fact that it doesn't fire is coming from valve code directly, so forcing these through may have unforeseen consequences

**Comment by KillStr3aK** [comment]
> I'm not sure we should really be changing this bool, because the fact that it doesn't fire is coming from valve code directly, so forcing these through may have unforeseen consequences

I agree
