### ISSUE TITLE
not loading properly

### ISSUE THREAD

**Issue by Soder-debug** [roflmuffin/CounterStrikeSharp#419]
So I think I have it installed right but when I run css_plugins list, to see if it works I get unknown command, but for some reason meta sees the plugins and says its loaded 

> meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (v213 @ dfc9859) by Roflmuffin
> css_plugins list
Unknown command 'css_plugins'!

**Comment by KillStr3aK** [comment]
did you install the `with-runtime` version?

**Comment by mayersgamer** [comment]
yes i did but same

**Comment by Pagefreak** [comment]
I can agree. Exact same issue.

**Comment by KillStr3aK** [comment]
you should share some logs aswell

**Comment by Soder-debug** [comment]
I fixed it by changing my provider, so basically what is happening is the
providers game image is wrong and it bugs it out. So change your game image
or if you can't through your provider then change providers and get a
refund.
