### ISSUE TITLE
Doesnt loading

### ISSUE THREAD

**Issue by sidasltu** [roflmuffin/CounterStrikeSharp#42]
Hi i install right but when i write to console css_plugins list its says that command doesnt exist when i write meta list i see that folder that mean to be a sharp its with no name and next writting <NOFILE>

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/85897059/2c25cafe-4324-4c56-8209-2a5d4eadf835)

**Comment by KillStr3aK** [comment]
Windows is not supported yet, there is a fork that can start on windows but full compatibility is not a thing yet

**Comment by sidasltu** [comment]
What kind of fork ? Where can I find it maybe some plugins will work I wanna try it

**Comment by KillStr3aK** [comment]
https://github.com/Ciallo-Ani/CounterStrikeSharp

its far from stable probably but you can give it a try

**Comment by sidasltu** [comment]
> https://github.com/Ciallo-Ani/CounterStrikeSharp
> 
> its far from stable probably but you can give it a try

Thanks.I try it but its doesnt work

**Comment by sidasltu** [comment]
> https://github.com/Ciallo-Ani/CounterStrikeSharp
> 
> its far from stable probably but you can give it a try

Also this installation working like, you get files and just drag to server side there is addon folder thats it ? Or you need something do more like editing some config file that will call this libarry like metamode ?

**Comment by KillStr3aK** [comment]
Windows is now supported, consider updating your artifact and runtime with the corresponding platform!
