### ISSUE TITLE
[Command Issue] SwitchTeam And Unassigned

### ISSUE THREAD

**Issue by pump4love** [roflmuffin/CounterStrikeSharp#43]
Hi, so we just stumbled upon this minor thing. 

I assume it is an issue on the end of CounterStrikeSharp and not CS2 itself, so take it with a grain of salt.
But I just so happened to stumble upon a minor thing with the SwitchTeam command, as I was trying to issue it on a player, with the team index of NONE, and 0. 

I had no errors with my compiler, and the plugin loads fine. But when the code is run, I receive the following output in my server console: 
CCSPlayerPawnBase::SwitchTeam( 0 ) - invalid team index.

What I am trying to do is to move a player to the 'unassigned' team.
I know it was possible to do in CS:GO, so I am just going out on a limb assuming the same applies here, albeit I am uncertain of whether it is the case. Hopefully, this is on the CounterStrikeSharp end of things and is an easy fix, and not an actual limitation.

**Comment by b0ink** [comment]
`CCSPlayerController.ChangeTeam(CsTeam team)` was added in 822115e that will allow you to switch a player to None(Unassigned)/Spectator/ T/CT
