### ISSUE TITLE
Plugin doesn't loaded with "CoreConfig file not found" error

### ISSUE THREAD

**Issue by OneDollarMan** [roflmuffin/CounterStrikeSharp#444]
Hello, cssharp suddenly stopped loading on all my servers, metamod is still working but meta list gives "no plugins loaded". I didn't made any changes except cs2 update. If I try to load plugin with "meta load <path>" command, it gives error "CoreConfig file not found.", but file exists
<img width="846" alt="Снимок экрана 2024-05-07 в 21 36 00" src="https://github.com/roflmuffin/CounterStrikeSharp/assets/52624425/021a26c6-5245-43d3-8a67-d31534c964ac">

I updated css plugin to ver.228 and now I receive recursive this, also core configs doesn't created in folder:
<img width="769" alt="Снимок экрана 2024-05-07 в 21 38 09" src="https://github.com/roflmuffin/CounterStrikeSharp/assets/52624425/58d2e358-9f8f-4e51-8353-7e49e029d563">

metamod version is 2.0.0-dev+1282
I gived owner privileges of server folder to steam user, but it doesn't changed anything
help please, how to fix this?

**Comment by sn0wyQ** [comment]
I am facing the same issue, it seems like [GameDirectory()](https://github.com/roflmuffin/CounterStrikeSharp/blob/11e5e9972d48d8280a2b35003b95f48a2c45aee7/src/core/utils.h#L13) returns empty string

**Comment by roflmuffin** [comment]
The minimum required version of Metamod after the update is v1290

**Comment by OneDollarMan** [comment]
> The minimum required version of Metamod after the update is v1290

I updated metamod to 1291 and made clean install of css with runtime but I receive the same recursive error
<img width="755" alt="Снимок экрана 2024-05-08 в 10 22 03" src="https://github.com/roflmuffin/CounterStrikeSharp/assets/52624425/608da120-63d6-45c4-8c7b-4820a533d306">

**Comment by roflmuffin** [comment]
It definitely seems like a file creation permission; whichever user is running the cs2 process does not have access to create `addons/counterstrikesharp/configs/core.json` using the contents of `addons/counterstrikesharp/configs/core.example.json`. So I would advise checking the folder permissions of `addons/counterstrikesharp/configs/` as well as the file permissions of `addons/counterstrikesharp/configs/core.example.json`

**Comment by OneDollarMan** [comment]
okay, thank you
permissions on files and folders seems to be good, i tried to change owner to steam, but nothing changes
I found a faster way to fix this, just copied configs from my old css and it worked
