### ISSUE TITLE
New CS2 Update Crashes server

### ISSUE THREAD

**Issue by pimpmyname2** [roflmuffin/CounterStrikeSharp#459]
23-05 update causes crash with: [00:56:38.859] CSSharp: Failed to find signature for 'Host_Say'
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/79339372/cfd27eba-a561-43e7-9f9f-481c45e64f1a)

**Comment by ThomasAdnum** [comment]
Yeah I cant connect either with new update :)

**Comment by mstankov** [comment]
+1 unfortunately. Seems like Valve did a poo poo

**Comment by y3request** [comment]
every single server on my favorites is down lol. i tried to disable/enable certain things, still does not start with cssharp disabled. I wonder if it is valve issue or metamod(combined?)

**Comment by crashzk** [comment]
Wait for an update from CSSharp.

**Comment by JeBenzon** [comment]
Is it Meta or Sharp related?

**Comment by Jano1959** [comment]
Almost 100 it's due to the latest Valve update, but yes, removing CSSharp, lets the server reboot.

**Comment by soren33322** [comment]
Same here.

**Comment by zonical** [comment]
We are aware of this issue and a fix is currently being worked on.

**Comment by zSniiKeR** [comment]
Same error here, with /game/cs2.sh line 118

**Comment by Ligge-Ligge** [comment]
Same here.

**Comment by zonical** [comment]
Rolfmuffin has released a patch - v234. Not all of the offsets have been tested, so if any more issues arise, please create a new request. Ngā mihi nui.
