### ISSUE TITLE
GetPlayers() sometimes return wrong list. (CS2 problem userid after mapchange)

### ISSUE THREAD

**Issue by IKiwky** [roflmuffin/CounterStrikeSharp#46]
Sometimes after map change one user id will be -256, which is valid one somehow.
In controller my userid is -256, in status is 65280, 65280 & FF = 0, real id.

```
for (int i = 0; i <= Server.MaxPlayers; i++)
{
    var controller = GetPlayerFromIndex(i);

    if (!controller.IsValid || controller.UserId < 0)
        continue;

    players.Add(controller);
}
```

Here, controller.UserId < 0 should not exists?

**Comment by roflmuffin** [comment]
Based on the fact that a user shows as `65280` in status, I'm guessing that means we should be representing userid as unsigned?

**Comment by roflmuffin** [comment]
I've implemented a somewhat temporary fix that just ignores `-1` explicitly, which should handle this case.

**Comment by IKiwky** [comment]
Displaying userid în scoreboard for exemple will have this problem too, with -256

Maybe something like,

public int? UserId
    {
        get
        {
            if (EntityIndex == null) return null;
            return NativeAPI.GetUseridFromIndex((int)(this.EntityIndex.Value.Value & 0xFF));
        }
    }

Will solve the problem.
