### ISSUE TITLE
GetClassBaseline: FindStringIndex

### ISSUE THREAD

**Issue by Mr-Robot-ops** [roflmuffin/CounterStrikeSharp#465]
CSSharp: v235
Metamod: build 1293

Linux 64 Bit
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

Dust 2
![grafik](https://github.com/roflmuffin/CounterStrikeSharp/assets/55334802/d2bcfafb-fd11-45e4-aa14-2eed63550e41)

Errors:
``GetClassBaseline: FindStringIndex(41-CCSPlayerPawn) failed``
``GetClassBaseline: FindStringIndex(39-CCSObserverPawn) failed``

Custom Map (seek_pool_home):
![grafik](https://github.com/roflmuffin/CounterStrikeSharp/assets/55334802/ba6c4917-c1a4-43a4-aed2-cfa6c4f03032)

Errors:
``GetClassBaseline: FindStringIndex(37-CCSGOViewModel) failed``
``GetClassBaseline: FindStringIndex(104-CKnife) failed``

When I activate my loadout plugin I get more errors regarding the grenades that are stored in my loadout config (https://github.com/oqyh/cs2-Spawn-Loadout-GoldKingZ/tree/main)
![grafik](https://github.com/roflmuffin/CounterStrikeSharp/assets/55334802/b5356efe-95c7-4556-a877-04dabee7090a)

Errors:
``GetClassBaseline: FindStringIndex(114-CMolotovGrenade) failed``
``GetClassBaseline: FindStringIndex(90-CHEGrenade) failed``
``GetClassBaseline: FindStringIndex(104-CKnife) failed``

**Comment by xLeviNx** [comment]
This shouldn't be related to cs#. What other plugins are you running?

**Comment by Mr-Robot-ops** [comment]
I have just removed all my plugins once:
``css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 0 plugins loaded.``

I think I'll try to check my game files for errors

![grafik](https://github.com/roflmuffin/CounterStrikeSharp/assets/55334802/33fa3232-c2f1-41d2-b235-0b6980554cd1)

**Comment by Mr-Robot-ops** [comment]
I'm already one step further.

I have found a problem with the Steam login. I have added
+app_update 730 validated \ and also added my API keys again.

Now I can start Dust2 again. But there is a new problem. I thought it was called "Fire update" and not "Fly update":
https://youtu.be/uSOlxJOFB10

**Comment by Mr-Robot-ops** [comment]
Okay, I have discovered the error and the solution. 

meta list

``[01] CounterStrikeSharp (v235 @ 3240a5e) by Roflmuffin``
  ``[02] <FAILED>``
  ``[03] ServerListPlayersFix (1.0.1) by Poggu``

ServerListPlayersFix caused the problem and Multiaddonmanager was also outdated.

Both were updated to the latest version and now the server is running again.
