### ISSUE TITLE
Please add Ukrainian language support to the plugin

### ISSUE THREAD

**Issue by panikajo** [roflmuffin/CounterStrikeSharp#471]
I encountered a problem that the Russian language works if you set it in the file, but the Ukrainian language does not, why is that so?

I added the `ua.json` file to the translations, added my translation to it, then went to `core.json` and indicated ua there, restarted the server, and it didn’t help me, the server displays English even though my client is even in Ukrainian.

**Comment by roflmuffin** [comment]
The language support is provided by the plugin; we currently don't offer any core translations at this time, so you would need to check with the particular plugin if they provide Ukrainian language support.

**Comment by panikajo** [comment]
> The language support is provided by the plugin; we currently don't offer any core translations at this time, so you would need to check with the particular plugin if they provide Ukrainian language support.
> 
> Note that we use the .NET localization library, where the 2 letter designation for Ukrainian is actually `uk` as seen in [this list](https://www.localeplanet.com/icu/) so ensure that the plugin is providing a `uk.json` file and the language on the server is set to `uk`.
uk? I tWhy uk? I thought uk was United Kingdom

**Comment by roflmuffin** [comment]
> > The language support is provided by the plugin; we currently don't offer any core translations at this time, so you would need to check with the particular plugin if they provide Ukrainian language support.
> > Note that we use the .NET localization library, where the 2 letter designation for Ukrainian is actually `uk` as seen in [this list](https://www.localeplanet.com/icu/) so ensure that the plugin is providing a `uk.json` file and the language on the server is set to `uk`.
> 
> uk? I tWhy uk? I thought uk was United Kingdom

en_GB is the ICU locale for the United Kingdom. But I didn't come up with the standard.

**Comment by panikajo** [comment]
Yes you are right it works. Thank you, sorry to bother you!
