### ISSUE TITLE
Problem/BUG -> EventEnterBuyzone & EventExitBuyzone

### ISSUE THREAD

**Issue by malloc2k** [roflmuffin/CounterStrikeSharp#476]
### **The Hooks to these events seem to be broken (at least for me)**

- I have tried to create a _**public HookResult (Post HookMode)**_  to both Enter and Exit Buyzones but it seems like it doesnt trigger the event at all...

Heres the code that I currently have:

```
public HookResult OnEnterBuyZone(EventEnterBuyzone @event, GameEventInfo info, HookMode post)
        {
            var player = @event.Userid;
            
            if(player == null || player.UserId == null)
                return HookResult.Continue;
            
            player.PrintToChat("Entered buyzone");

            return HookResult.Continue;
        }
```

**And the same goes for the Exit buyzone.** 

_This previously worked but after an update it doesnt anymore (im not sure which update)._

**Comment by KillStr3aK** [comment]
keep in mind that every game event is triggered by the game itself and its rare that something is wrong on our side in this context.
if its not fired then its possible that valve just stopped firing it at all

**Comment by malloc2k** [comment]
> keep in mind that every game event is triggered by the game itself and its rare that something is wrong on our side in this context. if its not fired then its possible that valve just stopped firing it at all

But its kinda weird tho!!
Why should it be like that?

**Comment by malloc2k** [comment]
Seems like the event does fire but it only works if I declare the hook to it on the old method
