### ISSUE TITLE
[Need Help] How to get Players?

### ISSUE THREAD

**Issue by ZWqPY** [roflmuffin/CounterStrikeSharp#484]
I was trying to find in the API how to get players on the server, or to be more precise, terrorists and counter-terrorists. However, it didn't work out for me. Can you help with this issue?

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/78861832/e145f26a-c4ca-4210-90a0-a6eef2bbb2a5)

**Comment by unqxl** [comment]
Use `Utilities.GetPlayers()` instead.

**Comment by ZWqPY** [comment]
thx!
