### ISSUE TITLE
How to obtain the player's current position?

### ISSUE THREAD

**Issue by YCcHxxt** [roflmuffin/CounterStrikeSharp#497]
I want to create a teleportation plugin similar to "kz", but regarding the issue of obtaining player positions, I have no idea where to start

**Comment by TitaniumLithium** [comment]
```ruby
            var player = Utilities.GetPlayerFromUserid(id);
            var pawn = player.PlayerPawn.Get();
            Vector Position = new Vector(x,y,z);
            pawn.Teleport(Position)
```

`Vector` [https://docs.cssharp.dev/api/CounterStrikeSharp.API.Modules.Utils.Vector.html](https://docs.cssharp.dev/api/CounterStrikeSharp.API.Modules.Utils.Vector.html)
`CCSPlayerController` [https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CCSPlayerController.html](https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CCSPlayerController.html)
`CCSPlayerPawn` [https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CCSPlayerPawn.html](https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CCSPlayerPawn.html)
`Teleport` [https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CBaseEntity.html#CounterStrikeSharp_API_Core_CBaseEntity_Teleport_CounterStrikeSharp_API_Modules_Utils_Vector_CounterStrikeSharp_API_Modules_Utils_QAngle_CounterStrikeSharp_API_Modules_Utils_Vector_](https://docs.cssharp.dev/api/CounterStrikeSharp.API.Core.CBaseEntity.html#CounterStrikeSharp_API_Core_CBaseEntity_Teleport_CounterStrikeSharp_API_Modules_Utils_Vector_CounterStrikeSharp_API_Modules_Utils_QAngle_CounterStrikeSharp_API_Modules_Utils_Vector_)

**Comment by KillStr3aK** [comment]
dont forget that for these kind of questions we have our discord available, this is not an issue
