### ISSUE TITLE
Sugestion: Upload a Nuget package

### ISSUE THREAD

**Issue by abnerfs** [roflmuffin/CounterStrikeSharp#50]
By creating a hello world plugin I had to download the CounterStrikeSharp.API.dll DLL and reference it in my project manually, I believe you could upload it to [Nuget packages](https://www.nuget.org/packages) (add a step to do that in Github Actions pipeline) so we can leverage a package manager to avoid referencing the DLL manually.

**Comment by KillStr3aK** [comment]
Afaik this is on the list, for fast support or questions like this you may want to join to the discord server to see what's inside or whats being discussed

**Comment by abnerfs** [comment]
I will join the server, thanks
