### ISSUE TITLE
Warcraft Exemple Crashing

### ISSUE THREAD

**Issue by KAxdq** [roflmuffin/CounterStrikeSharp#508]
The plugin crashes, especially when using abilities (using dash multiple times seems to cause a crash).

I want to use the example, but it keeps crashing. It's not very useful to try using something that doesn't work properly. :/

(Running solo in latest css version)

**Comment by xLeviNx** [comment]
Wait for the release of wc3. There is a author working on it.

**Comment by roflmuffin** [comment]
The warcraft example is quite old and not maintained at the moment and not intended for use as a public plugin at this stage.
