### ISSUE TITLE
How to point from the obtained "userid" to "CCSPlayerPawn"?

### ISSUE THREAD

**Issue by YCcHxxt** [roflmuffin/CounterStrikeSharp#509]
How to point from the obtained "userid" to "CCSPlayerPawn"?
I have obtained "userid", but I want to teleport the player with userid=2 to a certain location
Maybe the problem is relatively simple. I'm sorry to disturb everyone

**Comment by TitaniumLithium** [comment]
Almost Everything you can find in Doc : [https://docs.cssharp.dev/docs/reference/referencing-players.html](https://docs.cssharp.dev/docs/reference/referencing-players.html)
`var player = Utilities.GetPlayerFromUserid(userid);`
