### ISSUE TITLE
css_plugin load/unload problem

### ISSUE THREAD

**Issue by wudi-7mi** [roflmuffin/CounterStrikeSharp#518]
When load and unload plugins, it behaves different...

![PixPin_2024-06-29_05-53-56](https://github.com/roflmuffin/CounterStrikeSharp/assets/122330888/85f0c465-e615-4a3f-bb34-998150bb930d)
![PixPin_2024-06-29_05-54-35](https://github.com/roflmuffin/CounterStrikeSharp/assets/122330888/f49ccc20-a064-4bcb-9856-2370945c4a9c)

**Comment by Truba55** [comment]
Could this also be part of the problem? 

![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/28046241/0d5ed478-ce34-4650-863a-1a56b7401bb2)

**Comment by roflmuffin** [comment]
Hey, I'm updating the `css_plugin unload` to also work on file path, which will make it more consistent. You will not be able to load using the loaded plugin name ("Retakes Plugin" in this case), as that information is only known once the plugin has been loaded, so file path must always be used in that case.
