### ISSUE TITLE
No function without Metamod

### ISSUE THREAD

**Issue by BigSaVo** [roflmuffin/CounterStrikeSharp#528]
Hello everyone,
I have just downloaded the latest version of Css and uploaded it to my server. Now I wanted to download the latest Metamod version and noticed that you can't download a Metamod version. There is no longer a release version on Github to download Metamod 2.0. Can you maybe help me with how to get plugins to work on Cs2 servers in the future?

**Comment by SkyJust4Fun** [comment]
https://www.sourcemm.net/downloads.php/?branch=master u can... ?-?

**Comment by SkyJust4Fun** [comment]
Im using 1293, under download on the table select ur operating system..

**Comment by BigSaVo** [comment]
Hello, thanks for the help. Ticket can be closed again. Downloading with Metamod is working again
