### ISSUE TITLE
EventBuymenuOpen Missing Userid / CCSPlayerController

### ISSUE THREAD

**Issue by RealGoodAidan** [roflmuffin/CounterStrikeSharp#533]
According to [the docs](https://cs2.poggu.me/dumped-data/game-events/#buymenu_open), EventBuymenuOpen should have the User instance. However, it's missing: https://github.com/roflmuffin/CounterStrikeSharp/blob/5644921873663fada02f63ba70bbef60653d4cc0/managed/CounterStrikeSharp.API/Core/GameEvents.g.cs#L944

EventBuymenuClose has it: https://github.com/roflmuffin/CounterStrikeSharp/blob/5644921873663fada02f63ba70bbef60653d4cc0/managed/CounterStrikeSharp.API/Core/GameEvents.g.cs#L936

**Comment by roflmuffin** [comment]
Hey, we generate the game event classes based on the contents of the game events file in the vpk file, as seen below. This doesn't seem to have the userid defined.

Do you know if the value is valid if you do a manual `.Get<CCSPlayeraController>` on the event instance?

https://github.com/SteamDatabase/GameTracking-CS2/blob/9e73a086d6ecae1620e3ee94ade2fbb983d7499d/game/csgo/pak01_dir/resource/mod.gameevents#L396

**Comment by RealGoodAidan** [comment]
@roflmuffin I tried, but the hook doesn't seem to be working. I don't see my HERE log statement. I've tried both Pre/Post hooks. Maybe I'm doing something dumb.

```c#
[GameEventHandler(HookMode.Pre)]
    public HookResult OnBuymenuOpenPost(EventBuymenuOpen @event, GameEventInfo info)
    {
        Logger.LogInformation("HERE");
        Logger.LogInformation("{player} has opened the buy menu", @event.Get<CCSPlayerController>("userid").PlayerName);
        return HookResult.Continue;
    }
```

**Comment by RealGoodAidan** [comment]
Searching in your discord, getting the player who opened the buy menu just isn't possible: https://discord.com/channels/1160907911501991946/1160907912445710480/1197209710277963867

Which is really weird in my opinion because the action is so user-specific, but obviously nothing you can do about it.
