### ISSUE TITLE
CollisionGroup Needs Force Type Casting

### ISSUE THREAD

**Issue by TitaniumLithium** [roflmuffin/CounterStrikeSharp#534]
Not a big problem though.
```ruby
TestEntity.Collision.CollisionGroup = CollisionGroup.COLLISION_GROUP_DEFAULT;
```

Will Alert :
`Cannot cast CounterStrikeSharp.API.Modules.Entities.Constants.CollisionGroup to byte directly`

https://github.com/roflmuffin/CounterStrikeSharp/blob/5644921873663fada02f63ba70bbef60653d4cc0/managed/CounterStrikeSharp.API/Modules/Entities/Constants/CollisionGroup.cs#L19-L24

https://github.com/roflmuffin/CounterStrikeSharp/blob/5644921873663fada02f63ba70bbef60653d4cc0/managed/CounterStrikeSharp.API/Core/Schema/Classes/CCollisionProperty.g.cs#L49-L51

**Comment by KillStr3aK** [comment]
in general this is intended, could be added tho
also dont forget that changing collisions like that are not preferred
