### ISSUE TITLE
CCSPlayer_WeaponServices_CanUse doesn't work on linux

### ISSUE THREAD

**Issue by oylsister** [roflmuffin/CounterStrikeSharp#545]
From commit: https://github.com/roflmuffin/CounterStrikeSharp/commit/aa40d81a86d0196e11dec23d200ec2c3afea0cdf
the current signature doesn't work, there is no error nor crashing. Possibly requiring more investigation.

From discord discussion
https://discord.com/channels/1160907911501991946/1160907912445710480/1271853503341400105
https://discord.com/channels/1160907911501991946/1160907912445710480/1271514523580498034

**Comment by Yarukon** [comment]
try this > 55 48 8D 15 ? ? ? ? 48 89 E5 41 55 49 89 FD 41 54 49 89 F4

**Comment by GamerXCZ** [comment]
@roflmuffin please

**Comment by Poggicek** [comment]
Caused by outdated dynohook submodule. Fixed in https://github.com/qubka/DynoHook/commit/a08f01f9ee24dd23dcb46e2b5c7dad8d569352fe

**Comment by oylsister** [comment]
waiting for #556
