### ISSUE TITLE
The css_ban doesn't seem to be working anymore

### ISSUE THREAD

**Issue by Porcellacion** [roflmuffin/CounterStrikeSharp#549]
I have been trying multiple ways of banning a player from my server, but nothing works, and neither does the built-in CSS command:
`css_ban <target or steamid64> [duration] [reason]`

It is just for me, or is anybody else having issues with this?
My CSS version is 255

**Comment by mrc4tt** [comment]
You should post that to CS2-SimpleAdmin (if you use that plugin)

**Comment by daffyyyy** [comment]
> You should post that to CS2-SimpleAdmin (if you use that plugin)

Probably its not simpleadmin,
`<#userid or name> [time in minutes/0 perm] [reason]`
Thats command helper for css_ban in simpleadmin

**Comment by mrc4tt** [comment]
> Probably its not simpleadmin,
My bad daffyyy =D

**Comment by roflmuffin** [comment]
This will be based on whichever admin plugin you are using, as CS# doesn't come with an admin/ban system by default
