### ISSUE TITLE
Utilities.GetPlayers() not found

### ISSUE THREAD

**Issue by nosqd** [roflmuffin/CounterStrikeSharp#55]
i want to make command to set all players to 1hp but Utilities.GetPlayers() (from test plugin) not found
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/70067741/620480c1-d1a2-49b5-93e7-cae0b55adb07)

**Comment by KillStr3aK** [comment]
Update your artifact and reference (Afaik it is now also available on nuget!)

`dotnet add package CounterStrikeSharp.API --version 1.0.28`

**Comment by nosqd** [comment]
thank you
