### ISSUE TITLE
How to set speed?

### ISSUE THREAD

**Issue by truenoob141** [roflmuffin/CounterStrikeSharp#564]
Hello! How do I set the player/pawn speed? Using MovementServices.MaxSpeed only allows set it to a lower value. In the examples use of player.SetSpeed is commented.

**Comment by KillStr3aK** [comment]
for these kind of questions join to our discord server where this has been answered already and existing code snippets are available, this is not an issue

**Comment by truenoob141** [comment]
Thanks :) Solution is `player.PlayerPawn.Value.VelocityModifier`
