### ISSUE TITLE
problem release 264 

### ISSUE THREAD

**Issue by Weapon8** [roflmuffin/CounterStrikeSharp#571]
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

after update 263 -> last 264 
i've got a crash

**Comment by roflmuffin** [comment]
I will need some more information, how many plugins are you running? Can you reproduce with a single plugin?

**Comment by Weapon8** [comment]
I tried without plugin just metamod cs2 fixes player list and authfix I don't have any additional log because the server crashes
sorry for my english I'm french

**Comment by KillStr3aK** [comment]
> I tried without plugin just metamod cs2 fixes player list and authfix I don't have any additional log because the server crashes sorry for my english I'm french

can you provide the log files?

**Comment by B3none** [comment]
Please confirm whether this is an issue in the latest release, if it's still happening then please re-open this issue with clear steps to reproduce it.
