### ISSUE TITLE
rtv plugin doesnt work anymore

### ISSUE THREAD

**Issue by S3ri0uS90** [roflmuffin/CounterStrikeSharp#58]
rtv plugin configurated with ws: fy_pool_day in maps.txt eg.
plugin called: LiteMapChooser.

**Comment by KillStr3aK** [comment]
I think this issue should be opened on the mentioned plugins repository

**Comment by S3ri0uS90** [comment]
ok thanks

**Comment by S3ri0uS90** [comment]
all fine....
