### ISSUE TITLE
Unable to start CounterStrikeSharp, prompting for missing files

### ISSUE THREAD

**Issue by shoval-dev** [roflmuffin/CounterStrikeSharp#583]
The game was updated today with big changes and metamod is not working properly

`
Loaded /mnt/steam/cs2/game/bin/linuxsteamrt64/libserver_valve.so, got (nil)
 failed to dlopen /mnt/steam/cs2/game/bin/linuxsteamrt64/libserver_valve.so error=/mnt/steam/cs2/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
 failed to dlopen "/mnt/steam/cs2/game/bin/linuxsteamrt64/libserver_valve.so" error=/mnt/steam/cs2/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
Loaded libserver_valve.so, got (nil)
 failed to dlopen libserver_valve.so error=libserver_valve.so: cannot open shared object file: No such file or directory
 failed to dlopen "libserver_valve.so" error=libserver_valve.so: cannot open shared object file: No such file or directory
`

**Comment by mihaigsm2003** [comment]
for momment problem is metamod, is not started in new update. Wait for new metamode update

**Comment by gha241** [comment]
do you know when there will be an update?

**Comment by shoval-dev** [comment]
> do you know when there will be an update?

Thanks to the contributors, we've fixed it and it's functioning fine!
