### ISSUE TITLE
New Issues Linux SERVER ON 2024/10/04 8.25

### ISSUE THREAD

**Issue by AkonL** [roflmuffin/CounterStrikeSharp#589]
update metamod v1314;
update counterstrikesharp v267;

![13](https://github.com/user-attachments/assets/adb866a9-1415-4fd8-9af7-6790983820f4)
![14](https://github.com/user-attachments/assets/4dd337f6-a891-45ce-9363-a32614961c53)

crash servers.

**Comment by raszyniaczek** [comment]
Ive got different error 
![CSS Error](https://github.com/user-attachments/assets/4983abeb-7f42-439d-9e83-a5f771662039)

After this my server got crash.

Any ideas?

**Comment by AkonL** [comment]
@raszyniaczek  This is really amazing , my server dont loading csssharp 
my server os Debian 11.0

**Comment by raszyniaczek** [comment]
My loading Metamod and CSS but it crash. No errors in plugins.

**Comment by AkonL** [comment]
plugins be based on css , however css be based on metamod , my english so bad .

**Comment by AkonL** [comment]
@roflmuffin

**Comment by raszyniaczek** [comment]
i think server got crash after this error:

`CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`

**Comment by KillStr3aK** [comment]
> i think server got crash after this error:
> 
> 
> 
> `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`

maybe try it with the gamedata that is in #584

**Comment by rosecld** [comment]
server also crashes when changing the map. does not start with the workshop map

**Comment by raszyniaczek** [comment]
> > i think server got crash after this error:
> > `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`
> 
> maybe try it with the gamedata that is in #584

What exacly i need to swap from old build?? gamedata folder doesnt fix my error

**Comment by blekekok** [comment]
> > i think server got crash after this error:
> > `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`
> 
> maybe try it with the gamedata that is in #584

This fixed the issue, but I haven't tried installing CSS plugins yet

**Comment by 0x132406C** [comment]
[09:12:28.877] [info] CSSharp: Initializing
[09:12:28.877] [info] CSSharp: CoreConfig loaded.
[09:12:28.893] [info] CSSharp: Copying bytes from disk for D:/Program Files/steamcmd/steamapps/common/Counter-Strike Global Offensive/game/bin/win64/engine2.dll
[09:12:28.983] [info] CSSharp: Copying bytes from disk for D:/Program Files/steamcmd/steamapps/common/Counter-Strike Global Offensive/game/csgo/bin/win64/server.dll
[09:12:28.995] [info] CSSharp: Globals loaded.
[09:12:29.009] [info] CSSharp: Loading .NET runtime...
[09:12:29.010] [info] CSSharp: Loading hostfxr from D:\Program Files\steamcmd\steamapps\common\Counter-Strike Global Offensive\game\csgo/addons/counterstrikesharp\dotnet\host\fxr\8.0.3\hostfxr.dll
[09:12:29.010] [critical] CSSharp: unable to get export function: "hostfxr_initialize_for_runtime_config"
[09:12:29.010] [error] CSSharp: Failed to initialize .NET runtime.
[09:12:29.010] [error] CSSharp: Failed to initialize .NET runtime
[09:12:29.019] [error] CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst

in counterstrikesharp.log

**Comment by Ston3Cold** [comment]
> [09:12:28.877] [info] CSSharp: Initializing [09:12:28.877] [info] CSSharp: CoreConfig loaded. [09:12:28.893] [info] CSSharp: Copying bytes from disk for D:/Program Files/steamcmd/steamapps/common/Counter-Strike Global Offensive/game/bin/win64/engine2.dll [09:12:28.983] [info] CSSharp: Copying bytes from disk for D:/Program Files/steamcmd/steamapps/common/Counter-Strike Global Offensive/game/csgo/bin/win64/server.dll [09:12:28.995] [info] CSSharp: Globals loaded. [09:12:29.009] [info] CSSharp: Loading .NET runtime... [09:12:29.010] [info] CSSharp: Loading hostfxr from D:\Program Files\steamcmd\steamapps\common\Counter-Strike Global Offensive\game\csgo/addons/counterstrikesharp\dotnet\host\fxr\8.0.3\hostfxr.dll [09:12:29.010] [critical] CSSharp: unable to get export function: "hostfxr_initialize_for_runtime_config" [09:12:29.010] [error] CSSharp: Failed to initialize .NET runtime. [09:12:29.010] [error] CSSharp: Failed to initialize .NET runtime [09:12:29.019] [error] CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst
> 
> in counterstrikesharp.log

Yup, getting exactly the same on my side - here's hoping a fix can be deployed for this issue soon.

**Comment by raszyniaczek** [comment]
> > > i think server got crash after this error:
> > > `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`
> > 
> > 
> > maybe try it with the gamedata that is in #584
> 
> This fixed the issue, but I haven't tried installing CSS plugins yet

I have Windows server so it doesnt work for me. I dont know what to do.

**Comment by Ston3Cold** [comment]
> > > > i think server got crash after this error:
> > > > `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`
> > > 
> > > 
> > > maybe try it with the gamedata that is in #584
> > 
> > 
> > This fixed the issue, but I haven't tried installing CSS plugins yet
> 
> I have Windows server so it doesnt work for me. Its linux i think. I dont know what to do.

I'm on Windows too.

I changed the Windows address under the "IGameSystem_InitAllSystems_pFirst" section in gamedata.json to that which is listed for #584 . It still crashes with and without plugins loaded. In the log file it just doesn't say "CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst" any more. So yeah, something is still not right.

**Comment by raszyniaczek** [comment]
> > > > > i think server got crash after this error:
> > > > > `CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst`
> > > > 
> > > > 
> > > > maybe try it with the gamedata that is in #584
> > > 
> > > 
> > > This fixed the issue, but I haven't tried installing CSS plugins yet
> > 
> > 
> > I have Windows server so it doesnt work for me. Its linux i think. I dont know what to do.
> 
> I'm on Windows too.
> 
> I changed the Windows address under the "IGameSystem_InitAllSystems_pFirst" section in gamedata.json to that which is listed for #584 . It still crashes with and without plugins loaded. In the log file it just doesn't say "CSSharp: Failed to find address for IGameSystem_InitAllSystems_pFirst" any more. So yeah, something is still not right.

You think this is problem with CSS or Metamod?

**Comment by Ston3Cold** [comment]
> You think this is problem with CSS or Metamod?

I think maybe with CSS, although I could be wrong. Can just as well be the plugins too requiring an update to work with the latest version of CSS, which I hope isn't the case.

**Comment by raszyniaczek** [comment]
> > You think this is problem with CSS or Metamod?
> 
> I think maybe with CSS, although I could be wrong. Can just as well be the plugins too requiring an update to work with the latest version of CSS, which I hope isn't the case.

I update all important plugins.

**Comment by Ston3Cold** [comment]
> I update all important plugins.

I'm sorry, what do you mean, you updated the important plugins? Care to explain/elaborate for me, please? Does one need to change something on each plugin as well?

**Comment by raszyniaczek** [comment]
All plugins updated after new metamod release example MultiAddonManager

**Comment by blekekok** [comment]
After changing the gamedata to the one in #584 , it stopped the startup crash issues, but retake plugins by B3none crashes when the round starts. I'm not sure if its an MM or CSS or my machine's issue. But with 2 different installations, both of them crashes (LinuxGSM and Docker)

**Comment by raszyniaczek** [comment]
> After changing the gamedata to the one in #584 , it stopped the startup crash issues, but retake plugins by B3none crashes when the round starts. I'm not sure if its an MM or CSS or my machine's issue. But with 2 different installations, both of them crashes (LinuxGSM and Docker)

Im on WindowsGSM and mine doesnt start with this Gamedata

**Comment by Ston3Cold** [comment]
> After changing the gamedata to the one in #584 , it stopped the startup crash issues, but retake plugins by B3none crashes when the round starts. I'm not sure if its an MM or CSS or my machine's issue. But with 2 different installations, both of them crashes (LinuxGSM and Docker)

This fuels my suspicion that the actual plugins will need updates to make them compatible with the latest version of CSS most likely. Both the plugins I use (NockyCZ's DM and Kitsune's K4-System) crashes with 584's gamedata for me on Windows.

**Comment by raszyniaczek** [comment]
> > After changing the gamedata to the one in #584 , it stopped the startup crash issues, but retake plugins by B3none crashes when the round starts. I'm not sure if its an MM or CSS or my machine's issue. But with 2 different installations, both of them crashes (LinuxGSM and Docker)
> 
> This fuels my suspicion that the actual plugins will need updates to make them compatible with the latest version of CSS most likely. Both the plugins I use (NockyCZ's DM and Kitsune's K4-System) crashes with 584's gamedata for me on Windows.

What files i need to swap to try this working? only gamedata folder from CSS?

**Comment by Ston3Cold** [comment]
> What files i need to swap to try this working? only gamedata folder from CSS?
Yeah, only gamedata. Essentially its just the gamedata.json file inside the folder.

**Comment by Ston3Cold** [comment]
> 
> What files i need to swap to try this working? only gamedata folder from CSS?

Yes, the gamedata folder only had the gamedata.json file inside.

**Comment by raszyniaczek** [comment]
How to downlad this file? Sorry im new on Github :(

**Comment by raszyniaczek** [comment]
Ok its coming now to start but dont started. I disable all metamod plugins and it doesnt work.

**Comment by blekekok** [comment]
> > After changing the gamedata to the one in #584 , it stopped the startup crash issues, but retake plugins by B3none crashes when the round starts. I'm not sure if its an MM or CSS or my machine's issue. But with 2 different installations, both of them crashes (LinuxGSM and Docker)
> 
> 
> 
> This fuels my suspicion that the actual plugins will need updates to make them compatible with the latest version of CSS most likely. Both the plugins I use (NockyCZ's DM and Kitsune's K4-System) crashes with 584's gamedata for me on Windows. 

This is my first time attempting to create a CS2 server since CSGO. So, it's really bad timing to know if the plugin worked before the update or didn't. But it seems that I'm not the only one experiencing the issue.

**Comment by blekekok** [comment]
> > maybe it will help [link](https://github.com/roflmuffin/CounterStrikeSharp/issues/590#issuecomment-2393235577)
> 
> It doesnt work for me. I tried this on Windows Dedicated.
> 
> When first round start my server got crash.

I've tried this already, and encountered the same issue.

**Comment by blekekok** [comment]
Using #584 on its own, it doesn't crash the server, but when I tried 2 different retake plugins, it crashes either when the warmup ends, or randomly.

**Comment by blekekok** [comment]
Also there aren't any error logs, so I'm not sure what is causing it to crash.

**Comment by AkonL** [comment]
Time NOW 2024-10-4 20:22 Still not working , wite @roflmuffin to fix.....

**Comment by KillStr3aK** [comment]
> Time NOW 2024-10-4 20:22 Still not working , wite @roflmuffin to fix.....

the crash is known, issues will be resolved when possible. if you dont wan't to miss out, join to the discord server to receive latest announcements
