### ISSUE TITLE
ISSUES: 2024/10/04 22:31 IN Linux Debian 11.0 Crash 

### ISSUE THREAD

**Issue by AkonL** [roflmuffin/CounterStrikeSharp#596]
update css v268 Still appearing error
metamod 1314
css v268.
Debian 11.0
Game CS2

![1666](https://github.com/user-attachments/assets/8bdcc00c-ddf2-4b80-973d-f9d14f60613b)

@roflmuffin

**Comment by ZanderJi** [comment]
I have the same issue on windows server

**Comment by KillStr3aK** [comment]
> update css v268 Still appearing error metamod 1314 css v268. Debian 11.0 Game CS2
> 
> ![1666](https://private-user-images.githubusercontent.com/25493047/373680385-8bdcc00c-ddf2-4b80-973d-f9d14f60613b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTMxNTAsIm5iZiI6MTcyODA1Mjg1MCwicGF0aCI6Ii8yNTQ5MzA0Ny8zNzM2ODAzODUtOGJkY2MwMGMtZGRmMi00YjgwLTk3M2QtZjlkMTRmNjA2MTNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDE0NDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMGFhMmVlNTljMjQ3ZjUyMDllNGViZTI0YjM2ZmI0MTdmYTg2NzNiOTFkYWI1MTJkN2NhNjhmMzQ4NDRkYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l541hktRJK2UvvLiJWBwK0SMX0NnFM7ndliREmdvNdw)
> 
> @roflmuffin

these signatures are fixed with #584 (artifact v269)

**Comment by AkonL** [comment]
amazing @roflmuffin  269 runner ok .
