### ISSUE TITLE
Metamod 1314 + CSS 272 crashes server on Win10

### ISSUE THREAD

**Issue by fpaezf** [roflmuffin/CounterStrikeSharp#602]
Clean installation, no plugins installed, just MM and CSS.
Server crashes on initialization... These are the last console messages before crash:

![Sin título](https://github.com/user-attachments/assets/1376986d-8af7-4e55-83b4-4e786c31bbf6)

**Comment by Pintuzoft** [comment]
I get the same thing on Win11 for builds 270, 271 and 272. MM by itself is fine, then when I lift in a clean CSS (with runtime) without plugins the server crashes with that message

**Comment by fpaezf** [comment]
Seems Windows version is buggy.... waiting for a fix...

**Comment by 0x132406C** [comment]
I want to ask,how do you keep the console don't disappear?pls

**Comment by fpaezf** [comment]
Just a screenshot in the right moment...😅

**Comment by 0x132406C** [comment]
😂

**Comment by moises4863** [comment]
Same issue, i open sv tab and crash and automatically close tab 🫠

**Comment by KillStr3aK** [comment]
after local test #606 seems to fix this, however further crashes could happen as there are internal changes.

**Comment by fpaezf** [comment]
Great!, will try latter. Thank you for your hard work.❤️

**Comment by Pintuzoft** [comment]
just tried 276 and it seem to work fine now for me thanks! :)

**Comment by fpaezf** [comment]
Worked for me too!
