### ISSUE TITLE
Correct Signatures

### ISSUE THREAD

**Issue by danikfml** [roflmuffin/CounterStrikeSharp#603]
Does anyone have the right signatures for this?
CCSPlayer_CanAcquire, GetCSWeaponDataFromKey

**Comment by fuzzyscn** [comment]
"windows": "48 8B C4 44 89 40 ? 48 89 50 ? 48 89 48",
        "linux": "55 48 89 E5 41 57 41 56 48 8D 45 CC",
from swift, no test .

**Comment by danikfml** [comment]
for CCSPlayer_CanAcquire or GetCSWeaponDataFromKey
