### ISSUE TITLE
PrintToCenterHtml results in Segmentation Fault

### ISSUE THREAD

**Issue by mificot** [roflmuffin/CounterStrikeSharp#61]
For some reason **show_survival_respawn_status** event crash server. Code below was tested on three different servers with latest CS2 and CounterStrikeSharp versions. Do you have any idea what happend?

Operation System: Ubuntu 22.04 / Ubuntu 22.10

Simple reproduction code
```C#
using CounterStrikeSharp.API.Core;

namespace TestPlugin;

public class TestPlugin : BasePlugin
{
    public override string ModuleName => "TestPlugin";

    public override string ModuleVersion => "0.0.0";

    public override void Load(bool hotReload)
    {
        base.Load(hotReload);

        AddCommand("test", "test", (player, info) => {
            if (player == null) {
                return;
            }

            player.PrintToCenterHtml("<font color=\"red\">TEST</font>");
        });
    }
}
```

Metamod list and css version
```
meta list
Listing 1 plugin:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
css
  CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: 30
```

**Comment by mificot** [comment]
Resolved by rebuilding sources.

**Comment by Dliix66** [comment]
@mificot What resources did you rebuild?

**Comment by mificot** [comment]
@Dliix66 i've rebuilded the whole project and managed CounterStrikeSharp.API and update the server addons as well as API dll in my plugin sources. For some reason dll from actions don't work for me, but when i build it myself it works
