### ISSUE TITLE
[Need Help] About "Player.Buttons"

### ISSUE THREAD

**Issue by DearCrazyLeaf** [roflmuffin/CounterStrikeSharp#638]
Im working on a plugin using CSSharp, and I want players to toggle it by using their bottons.

So here comes the problem, how can I know the default keys of these flags are? I hope to use "F" to toggle.

Code:
`if ((player.Buttons & PlayerButtons.flags here) != 0)`
Flags:
> 1.use
2.left 
3.run 
4.bullrush 
5.walk 
6.back 
7.alt1 
8.alt2 
9.attack 
10.attack2 
11.attack3 
12.cancel 
13.duck 
14.forward 
15.grenade1 
16.grenade2 
17.jump 
18.moveleft 
19.moveright 
20.reload 
21.right 
22.speed 
23.weapon1 
24.weapon2 
25.zoom

Exmaple:
![63a07137d70ab1400574ba4631de6842](https://github.com/user-attachments/assets/7adcdf33-a117-4a83-ace3-6c16ac48c297)

**Comment by crashzk** [comment]
Nothing to do with the subject, but try it on discord: https://discord.gg/eAZU3guKWU

GitHub Issues is focused more on CSSharp bugs etc. Help, questions like this can be addressed on discord, it's even faster.
