### ISSUE TITLE
Can I fork out a Chinese version of your warehouse? I originally planned to use it myself, but I want to keep it on Github

### ISSUE THREAD

**Issue by Max66888** [roflmuffin/CounterStrikeSharp#64]
Can I fork out a Chinese version of your warehouse? I originally planned to use it myself, but I want to keep it on Github

https://github.com/Max66888/MatchZy-Chinese

**Comment by KillStr3aK** [comment]
Please keep these discussions on the related plugin's repository as it is not related to CounterStrikeSharp.

**Comment by Max66888** [comment]
> [贡献者 ](https://github.com/roflmuffin/CounterStrikeSharp/commits?author=KillStr3aK)
> ###

Sorry, I just realized that I sent the wrong message
