### ISSUE TITLE
Some functional suggestions

### ISSUE THREAD

**Issue by Max66888** [roflmuffin/CounterStrikeSharp#65]
Based on my previous experience using Pug, may I ask if it is possible to add features such as

1.Vote for maps before starting the competition (very important)
2.Administrators can set whether to disrupt the team (very important)
3.Add a prompt box below the warm-up time prompt
4.Add [Ready] to the player name prefix on the scoreboard
5.Whether to enable edge selection in blade games when adding players to cast screens (convenient for me to copy this function to add other votes)

This is an important option for the competition function in the first part
I have many ideas about improving the completeness of functions, based on my long-term experience

Also, can we achieve registration setting Commands like sm_setting are much more convenient for administrators to control on the console

Thanks a lot !

**Comment by KillStr3aK** [comment]
Please keep these discussions on the related plugin's repository as it is not related to CounterStrikeSharp.

**Comment by Max66888** [comment]
> 请将这些讨论保留在相关插件的存储库中，因为它与 CounterStrikeSharp 无关。

Sorry, I just realized that I sent the wrong message
