### ISSUE TITLE
Error loading file or assembly SQLitePCLRaw.core

### ISSUE THREAD

**Issue by drakin003** [roflmuffin/CounterStrikeSharp#657]
Hello, I'm encountering an issue while trying to reload the MatchZy plugin in CSSharp, the plugin is unloading automatically because of this, I have attached the full log file for your review.

### Error Summary:
```
2024-11-04 14:10:34.330 +00:00 [INFO] (cssharp:PluginContext) Reloading plugin MatchZy
2024-11-04 14:10:34.333 +00:00 [INFO] (cssharp:PluginContext) Unloading plugin MatchZy
2024-11-04 14:10:34.338 +00:00 [INFO] (cssharp:PluginContext) Finished unloading plugin MatchZy
2024-11-04 14:10:34.355 +00:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'SQLitePCLRaw.core, Version=2.1.4.1835, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. An operation is not legal in the current state. (0x80131509)
```

### Environment:
CSSharp version: v284
MatchZy version: 0.8.6
OS: Ubuntu 22.04

Log File:
[log-all20241104.txt](https://github.com/user-attachments/files/17619664/log-all20241104.txt)

**Comment by Ferks-FK** [comment]
You should contact the author of the plugin for problems related to it.

**Comment by drakin003** [comment]
> You should contact the author of the plugin for problems related to it.

isn't SQLitePCLRaw.core in cssharp and not in matchzy plugin? sorry but not good at this

**Comment by Ferks-FK** [comment]
> > You should contact the author of the plugin for problems related to it.
> 
> isn't SQLitePCLRaw.core in cssharp and not in matchzy plugin? sorry but not good at this

it's a dependency of the plugin, not a cs# error.
