### ISSUE TITLE
Revisit changes made in #661

### ISSUE THREAD

**Issue by Poggicek** [roflmuffin/CounterStrikeSharp#684]
I am all for preventing developers from stuff that will only lead to broken behavior, however in this case I don't think anything is wrong with the behavior addressed in the #661 except for not meeting developer's expectations, the original PR did not include any cases where this could be bad in any way.

the `Teleport` method is a general function targeted at any entity, including the controller, it's not a special method with specific behavior for each entity.

These changes have only made the code ambiguous and instead of developers learning the difference between controllers and pawns it tries to smooth out the line between them, creating only more confusion.

Please do join the discussion below this issue and say what your perspective on this is.

**Comment by Poggicek** [comment]
Extending the controller class with let's say `TeleportPawn` that does all the pawn sanity checks sounds a lot more sensibl

**Comment by zonical** [comment]
Joining the discussion after talking on the Discord. I agree with @Poggicek that we should push developers to learn the differences between pawns and controllers rather than create edge-case solutions. 

xstage on Discord suggested adding a warning message to `Teleport` (and any other functions that may need it) when run from CCSPlayerController saying something along the lines of "you may have intended to target the player pawn instead" - and direct the developer [to the wiki with the appropriate documentation](https://docs.cssharp.dev/docs/reference/referencing-players.html) - maybe with an accompanying core config value disabling the warning if the developer knows what they're doing. Perhaps we could also re-arrange the article so the reference section is closer to the top and more visible to developers.

**Comment by qstage** [comment]
Maybe something like this. We will hide the `Teleport` method in `CCSPlayerController` and using the Obsolute attribute we will output a warning when compiling.

![image](https://github.com/user-attachments/assets/b8b6043a-a11e-4ef8-a8c6-887e3dfb4795)

**Comment by zonical** [comment]
> Maybe something like this. We will hide the `Teleport` method in `CCSPlayerController` and using the Obsolute attribute we will output a warning when compiling.
> 
> ![image](https://private-user-images.githubusercontent.com/166386817/389227281-b8b6043a-a11e-4ef8-a8c6-887e3dfb4795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzOTc0MjIsIm5iZiI6MTczMjM5NzEyMiwicGF0aCI6Ii8xNjYzODY4MTcvMzg5MjI3MjgxLWI4YjYwNDNhLWExMWUtNGVmOC1hOGM2LTg4N2UzZGZiNDc5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QyMTI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTdiMjkzNjQ4MjY4NTVlN2M4NjFhYmY5YWM3NDRlOWUxNzRlYzM5ZDZjNDk0ODVmOWU5NDUxZjNiZjIyNTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8G-QcWff_FEhuE_t-StCrRSfNxRc4cqRPBq-it9WtCU)

Part of me wishes there was a custom `[Warning]` attribute in C#, but this seems like an alright solution to me.

**Comment by Poggicek** [comment]
> Maybe something like this. We will hide the `Teleport` method in `CCSPlayerController` and using the Obsolute attribute we will output a warning when compiling.
> 
> ![image](https://private-user-images.githubusercontent.com/166386817/389227281-b8b6043a-a11e-4ef8-a8c6-887e3dfb4795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzOTg2NDMsIm5iZiI6MTczMjM5ODM0MywicGF0aCI6Ii8xNjYzODY4MTcvMzg5MjI3MjgxLWI4YjYwNDNhLWExMWUtNGVmOC1hOGM2LTg4N2UzZGZiNDc5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QyMTQ1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGNjMTZiNjM2ZTVjZGFjZmIyN2QyZWRjZjAyZGI3YzIxZmVmZTUxZDFmNDM4NWM1YTRkZjJjY2QyZjIyZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sAL5J3oDobOcfnLMtO6pAi3dd8FPF4PgO-ejynvkC3g)

sounds good, I'd just rather use the more generic Pawn rather than PlayerPawn, there's a big difference.

**Comment by roflmuffin** [comment]
I've raised a PR reverting the functionality and adding an obsolete compiler warning to just the ccsplayercontroller class instead. I would like to avoid runtime warnings if possible. Open to adding a new `TeleportPawn` helper method but I think honestly people should just null chain to the pawn teleport manually and be explicit.
