### ISSUE TITLE
CSS fails to load latest update,

### ISSUE THREAD

**Issue by ImInTheICU** [roflmuffin/CounterStrikeSharp#715]
```./game/cs2.sh: line 98:    46 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"```
When loading CSS on latest update with latest MetaMod and CSS.

**Comment by skywalkerja** [comment]
Can confirm. Same issue  on my CS2 Dedicated Server

**Comment by selisheeno** [comment]
You need to wait for CSS UPDATE i think it will be soon

**Comment by AWJoki** [comment]
same isue Here... 
 soo far what i can see its affects on linux maschines.. i seen few windows server that is up and working... 
i guess its a signature error ??

**Comment by WellFREEzZ** [comment]
Same

**Comment by selisheeno** [comment]
https://github.com/samyycX/CounterStrikeSharp/releases/tag/v7

try this

**Comment by AWJoki** [comment]
> https://github.com/samyycX/CounterStrikeSharp/releases/tag/v7
> 
> try this

it Looks to work .. ubuntu 23.10 with metamod 1315.. 
What is the difference? from orginal?

**Comment by ImInTheICU** [comment]
Fixed using. https://github.com/samyycX/CounterStrikeSharp/releases/tag/v7.
