### ISSUE TITLE
AdminManager improvements

### ISSUE THREAD

**Issue by zonical** [roflmuffin/CounterStrikeSharp#73]
This is just a collection of some ideas that people have been discussing in the Discord to improve the AdminManager API:

- Add groups of permissions to simplify how many flags are required. This can probably be enforced by including a syntax for individual flags `@` and groups of flags `#`
- Remove all arbitrary flags from core e.g `can_execute_css_commands`
- Add wildcard support for RequiresPermissions and PlayerHasPermissions e.g `@css/*`
- Add OR support for RequiresPermissions, this can probably be done with a simple bool argument

**Comment by crashzk** [comment]
Can we expect immunity system? Something similar that already exists in SourceMod.

https://github.com/roflmuffin/CounterStrikeSharp/issues/41

> ~Can we still expect this since the mentioned PR has been closed?~
> 
> From what I saw it was implemented: https://docs.cssharp.dev/features/admin-framework/
> 
> Curiosity, can we expect an immunity system in the future?
> 
> In other words, administrators with immunity 90 are not affected by administrators with immunity below 90 or less.
