### ISSUE TITLE
V44 Server Crash / Errors when using Server.PrintToChatAll function

### ISSUE THREAD

**Issue by Quantor97** [roflmuffin/CounterStrikeSharp#75]
The title says all. When using the print function the server gives a weird error like "signature not found" and crashes in some circumstances

To reproduce:
use the function

**Comment by daffyyyy** [comment]
same with **Remove** method on **CBasePlayerWeapon**

**Comment by KillStr3aK** [comment]
This has been fixed in 414710d05cedf7e7a9de44f36067bac71aca4b2d
