### ISSUE TITLE
admin permissions

### ISSUE THREAD

**Issue by asdfxD** [roflmuffin/CounterStrikeSharp#81]
added myself as admin but it doesn't work, i get always.

[CSS] You do not have the correct permissions to execute this command.

**Comment by DOK-26-RUS** [comment]
this solved it
![admins](https://github.com/roflmuffin/CounterStrikeSharp/assets/150077502/aaa5430c-d369-4466-8fb7-0c23303085fb)
It was in the Discord support branch
https://discord.com/channels/1160907911501991946/1160907912445710480/1173390332797403267

**Comment by asdfxD** [comment]
downloaded the last build but still no, it does not work for me.

{
  "'XXXX: {
    "identity": "7656XXXXXXXXXXXXX",
    "flags": [
	  "can_execute_css_commands",
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ]
  },

**Comment by DOK-26-RUS** [comment]
"'XXXX: { - is this a typo? 

must be
{
  "Erikj": {
    "identity": "7656*************",
    "flags": [
      "can_execute_css_commands",
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ]

**Comment by asdfxD** [comment]
No, its just cenaored. It does not work.

**Comment by DOK-26-RUS** [comment]
"'XXXX: { I asked because you missed " after X

**Comment by KillStr3aK** [comment]
progress on admin system: https://github.com/roflmuffin/CounterStrikeSharp/pull/74

**Comment by KillStr3aK** [comment]
this might be closed?
