### ISSUE TITLE
Is there any way/plan to communicate between plugins like delegate/event/shared data dict?

### ISSUE THREAD

**Issue by chenbuyi2019** [roflmuffin/CounterStrikeSharp#82]
For the moment, I didn't find a easy way to that.   

For example, I store players money in database. and I build different plugins to read/write it.  
It might be a waste if I make a new Mysql connection on each plugin.  

I am thinking to build a ASP .NET Core app running alone,  
and use a shared Library which contains http/websocket api on each plugin.

**Comment by KillStr3aK** [comment]
Sharing data between plugins is on the table of plans currently

with API reading from mysql you are good to go

**Comment by laper32** [comment]
Please see #71, we're planning on it.

**Comment by chenbuyi2019** [comment]
Glad to see you. Thanks.
