### ISSUE TITLE
Admin Immunity

### ISSUE THREAD

**Issue by AnthonySil** [roflmuffin/CounterStrikeSharp#83]
I was vote kicked on my own server and temporary banned even tho i am css admin!

I set myself as admin in the admins.json file. most commands dont work or maybe i dont know how to use them? however i can use css_rcon so i been getting by with that.

Here are my flags
    "flags": [
      "can_execute_css_commands",
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ]

earlier today i joined my server. at the last round map changed and as soon as the new map started someone started a vote to kick me. I was kicked and could not rejoin the server. so i shut it down! any suggestions would be greatly appreciated.

Thanks

**Comment by dran1x** [comment]
I think you should disable the in-game voting system because there really isn't anything we can do about it in terms of interacting with it.

sv_allow_votes <0 / 1>

**Comment by DOK-26-RUS** [comment]
use "sv_vote_issue_kick_allowed 0" to disable voting for a kick

**Comment by KillStr3aK** [comment]
`css admin` comes with template permissions that are not being used at all by the core as they only serve as a template.

progress on admin system: https://github.com/roflmuffin/CounterStrikeSharp/pull/74

**Comment by roflmuffin** [comment]
Will be closed by #74

**Comment by KillStr3aK** [comment]
this should be closed by now
