### ISSUE TITLE
Some colors are wrong.

### ISSUE THREAD

**Issue by asdfxD** [roflmuffin/CounterStrikeSharp#85]
LightBlue is Lila (Purple) for example.

**Comment by asdfxD** [comment]
done, too fast enter sry.

**Comment by miguno** [comment]
Can confirm.  `ChatColors.LightYellow` also renders like `ChatColors.Purple`.

**Comment by asdfxD** [comment]
\x05 should be lightgreen as in csgo, is use \x05 in cs2fixes and its lightgreen.

**Comment by asdfxD** [comment]
Look in ChatColors.cs LightBlue and LightYellow use same color, \x03 as Purple.

![l](https://github.com/roflmuffin/CounterStrikeSharp/assets/24253340/20b861a9-3273-49c3-9067-29ba1f9e1726)

**Comment by roflmuffin** [comment]
I need to do some further testing on this one and then I will update

**Comment by roflmuffin** [comment]
I've updated the colors and double checked and also added a new `LightPurple` color. This fix is in build v71
