### ISSUE TITLE
Bug: `DeregisterEventHandler` and `RemoveListener` do not work

### ISSUE THREAD

**Issue by l1monenko** [roflmuffin/CounterStrikeSharp#92]
After using these functions, the callbacks still work.

**Comment by KillStr3aK** [comment]
![image](https://github.com/roflmuffin/CounterStrikeSharp/assets/19509520/c3d919e3-40be-4c99-ba3b-ce2c68ec29e0)

I'll just leave this here

**Comment by l1monenko** [comment]
I tried to use `DeregisterEventHandler` in the following way, first I register the event `RegisterEventHandler<EventRoundEnd>(OnRoundEnd)`, then in the callback OnRoundEnd after its call `DeregisterEventHandler("round_end", OnRoundEnd, false)`, but the callback OnRoundEnd is still called after the end of the round.

**Comment by roflmuffin** [comment]
> I tried to use `DeregisterEventHandler` in the following way, first I register the event `RegisterEventHandler<EventRoundEnd>(OnRoundEnd)`, then in the callback OnRoundEnd after its call `DeregisterEventHandler("round_end", OnRoundEnd, false)`, but the callback OnRoundEnd is still called after the end of the round.

Hookmode is post by default, so I believe it should be: `DeregisterEventHandler("round_end", OnRoundEnd, true)`

**Comment by l1monenko** [comment]
> > I tried to use `DeregisterEventHandler` in the following way, first I register the event `RegisterEventHandler<EventRoundEnd>(OnRoundEnd)`, then in the callback OnRoundEnd after its call `DeregisterEventHandler("round_end", OnRoundEnd, false)`, but the callback OnRoundEnd is still called after the end of the round.
> 
> Hookmode is post by default, so I believe it should be: `DeregisterEventHandler("round_end", OnRoundEnd, true)`

I tried `DeregisterEventHandler("round_end", OnRoundEnd, true)` but also without result.

**Comment by l1monenko** [comment]
@roflmuffin Is it still an issue?

**Comment by roflmuffin** [comment]
As long as you use the same function reference that was originally used when you called register (and with the same post bool) then yes, it should work.

**Comment by ssypchenko** [comment]
Here is the basic test confirming that DeregisterEventHandler does not deregister event:
`using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Core.Plugin;
using CounterStrikeSharp.API.Core.Attributes.Registration;
using CounterStrikeSharp.API.Modules.Commands;
using CounterStrikeSharp.API.Modules.Utils;

namespace TestPlugin
{
    public class TestPlugin : BasePlugin
    {   
        public override string ModuleName => "Test Plugin";
        public override string ModuleVersion => "v1.0.0";
        public override void Load(bool hotReload)
        {
            Console.WriteLine($"Test started");
        }
        public override void Unload(bool hotReload)
        {
            //
        }

        [ConsoleCommand("teston", "Test")]
        public void OnTestCommand(CCSPlayerController? pc, CommandInfo command)
        {
            Console.WriteLine("Set PlayerSpawn on");
            RegisterEventHandler<EventPlayerSpawn>(OnPlayerSpawnHandler);
        }
        [ConsoleCommand("testoff", "Test")]
        public void OnTestOffCommand(CCSPlayerController? pc, CommandInfo command)
        {
            Console.WriteLine("Set PlayerSpawn off");
            DeregisterEventHandler("player_spawn", OnPlayerSpawnHandler, false);
        }
        private HookResult OnPlayerSpawnHandler (EventPlayerSpawn @event, GameEventInfo info)
        {
            var playerController = @event.Userid; 
            if (playerController == null || !playerController.IsValid || playerController.IsHLTV) {
                return HookResult.Continue;
            }
            Server.PrintToChatAll("Registered");
            return HookResult.Continue;
        }`
        
There is no "Registered" in the chat on plugin start.
There is "Registered" in the chat on every respawn after the command "teston"
There is "Registered" in the chat on every respawn after the command "testoff" (which should deregister the handler)

**Comment by ssypchenko** [comment]
@roflmuffin I know you have a lot to do. So this is just a gentle reminder that you "'ll be happy to look into it."

**Comment by roflmuffin** [comment]
I did have an initial look using the repro code you supplied, and was able to replicate it, but also not entirely sure why its happening. We use a dictionary to store these handlers and then it removes the handler based on the dictionary look up, but for some reason the identity is different, perhaps due to the untyped nature of `DeregisterEventHandler` vs `RegisterEventHandler<T>`

**Comment by B3none** [comment]
Here's a working version of me registering and de-registering an `OnTick` listener:
https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Modules/Menu/CenterHtmlMenu.cs#L65-L129

**Comment by ssypchenko** [comment]
> Here's a working version of me registering and de-registering an `OnTick` listener: 
@B3none 
Listeners are registered and removed correctly. Events handlers are not :(

@roflmuffin 
Do you mean in your explanations that something is wrong with the syntaxis? 
I tried in this way:
```
RegisterEventHandler<EventPlayerSpawn>(OnPlayerSpawnHandler);
private HookResult OnPlayerSpawnHandler<T>(T @event, GameEventInfo info) where T : GameEvent
{
//code
}
DeregisterEventHandler("player_spawn", OnPlayerSpawnHandler<EventPlayerSpawn>, true);```
The result is the same, the event is still active :( 
Could you please help me to find a way how to do it correctly? 
It may be convenient to deregister events for some reasons. Now I have to use global variable and hookresult.continue when it false. But this is not clean :(

**Comment by roflmuffin** [comment]
> > Here's a working version of me registering and de-registering an `OnTick` listener:
> 
> @B3none Listeners are registered and removed correctly. Events handlers are not :(
> 
> @roflmuffin Do you mean in your explanations that something is wrong with the syntaxis? I tried in this way:
> 
> ```
> RegisterEventHandler<EventPlayerSpawn>(OnPlayerSpawnHandler);
> private HookResult OnPlayerSpawnHandler<T>(T @event, GameEventInfo info) where T : GameEvent
> {
> //code
> }
> DeregisterEventHandler("player_spawn", OnPlayerSpawnHandler<EventPlayerSpawn>, true);
> ```
> 
> The result is the same, the event is still active :( Could you please help me to find a way how to do it correctly? It may be convenient to deregister events for some reasons. Now I have to use global variable and hookresult.continue when it false. But this is not clean :(

No there is nothing wrong with your syntax, I believe it is an issue on our end since the register requires a strongly typed `T` type event handler but the deregister event handler accepts any `Delegate`

**Comment by roflmuffin** [comment]
There is now a `DeregisterEventHandler<T>` which should fix this problem if you would be able to try that. It should be in v208.

**Comment by ssypchenko** [comment]
> There is now a `DeregisterEventHandler<T>` which should fix this problem if you would be able to try that. It should be in v208.

Yes, it works Ok now. Thank you!
