### ISSUE TITLE
read me not clear for simple users

### ISSUE THREAD

**Issue by mayersgamer** [roflmuffin/CounterStrikeSharp#96]
this mod is installed succesfully but i dont know where are the commands ? not single tutorial present on google already did a little search.

css_changemap ? 
css_kick 
css_ban 
css_slay 

how to check if im an admin , i set the id in admin.jason

**Comment by roflmuffin** [comment]
The system does not include any inbuilt plugins by default, at the moment it is in early stages and is mostly for plugin authors to develop and test.
